// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:kaiteki/fediverse/model/emoji/category.dart';
import 'package:kaiteki/fediverse/model/emoji/emoji.dart';

final peopleBody = <EmojiCategoryItem<UnicodeEmoji>>[
  const EmojiCategoryItem(
    const UnicodeEmoji("🙇"), [
      const UnicodeEmoji("🙇"),
      const UnicodeEmoji("🙇🏻"),
      const UnicodeEmoji("🙇🏼"),
      const UnicodeEmoji("🙇🏽"),
      const UnicodeEmoji("🙇🏾"),
      const UnicodeEmoji("🙇🏿"),
      const UnicodeEmoji("🙇‍♀️"),
      const UnicodeEmoji("🙇🏻‍♀️"),
      const UnicodeEmoji("🙇🏼‍♀️"),
      const UnicodeEmoji("🙇🏽‍♀️"),
      const UnicodeEmoji("🙇🏾‍♀️"),
      const UnicodeEmoji("🙇🏿‍♀️"),
      const UnicodeEmoji("🙇‍♂️"),
      const UnicodeEmoji("🙇🏻‍♂️"),
      const UnicodeEmoji("🙇🏼‍♂️"),
      const UnicodeEmoji("🙇🏽‍♂️"),
      const UnicodeEmoji("🙇🏾‍♂️"),
      const UnicodeEmoji("🙇🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🙋"), [
      const UnicodeEmoji("🙋"),
      const UnicodeEmoji("🙋🏻"),
      const UnicodeEmoji("🙋🏼"),
      const UnicodeEmoji("🙋🏽"),
      const UnicodeEmoji("🙋🏾"),
      const UnicodeEmoji("🙋🏿"),
      const UnicodeEmoji("🙋‍♀️"),
      const UnicodeEmoji("🙋🏻‍♀️"),
      const UnicodeEmoji("🙋🏼‍♀️"),
      const UnicodeEmoji("🙋🏽‍♀️"),
      const UnicodeEmoji("🙋🏾‍♀️"),
      const UnicodeEmoji("🙋🏿‍♀️"),
      const UnicodeEmoji("🙋‍♂️"),
      const UnicodeEmoji("🙋🏻‍♂️"),
      const UnicodeEmoji("🙋🏼‍♂️"),
      const UnicodeEmoji("🙋🏽‍♂️"),
      const UnicodeEmoji("🙋🏾‍♂️"),
      const UnicodeEmoji("🙋🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("💁"), [
      const UnicodeEmoji("💁"),
      const UnicodeEmoji("💁🏻"),
      const UnicodeEmoji("💁🏼"),
      const UnicodeEmoji("💁🏽"),
      const UnicodeEmoji("💁🏾"),
      const UnicodeEmoji("💁🏿"),
      const UnicodeEmoji("💁‍♀️"),
      const UnicodeEmoji("💁🏻‍♀️"),
      const UnicodeEmoji("💁🏼‍♀️"),
      const UnicodeEmoji("💁🏽‍♀️"),
      const UnicodeEmoji("💁🏾‍♀️"),
      const UnicodeEmoji("💁🏿‍♀️"),
      const UnicodeEmoji("💁‍♂️"),
      const UnicodeEmoji("💁🏻‍♂️"),
      const UnicodeEmoji("💁🏼‍♂️"),
      const UnicodeEmoji("💁🏽‍♂️"),
      const UnicodeEmoji("💁🏾‍♂️"),
      const UnicodeEmoji("💁🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🙆"), [
      const UnicodeEmoji("🙆"),
      const UnicodeEmoji("🙆🏻"),
      const UnicodeEmoji("🙆🏼"),
      const UnicodeEmoji("🙆🏽"),
      const UnicodeEmoji("🙆🏾"),
      const UnicodeEmoji("🙆🏿"),
      const UnicodeEmoji("🙆‍♀️"),
      const UnicodeEmoji("🙆🏻‍♀️"),
      const UnicodeEmoji("🙆🏼‍♀️"),
      const UnicodeEmoji("🙆🏽‍♀️"),
      const UnicodeEmoji("🙆🏾‍♀️"),
      const UnicodeEmoji("🙆🏿‍♀️"),
      const UnicodeEmoji("🙆‍♂️"),
      const UnicodeEmoji("🙆🏻‍♂️"),
      const UnicodeEmoji("🙆🏼‍♂️"),
      const UnicodeEmoji("🙆🏽‍♂️"),
      const UnicodeEmoji("🙆🏾‍♂️"),
      const UnicodeEmoji("🙆🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🙅"), [
      const UnicodeEmoji("🙅"),
      const UnicodeEmoji("🙅🏻"),
      const UnicodeEmoji("🙅🏼"),
      const UnicodeEmoji("🙅🏽"),
      const UnicodeEmoji("🙅🏾"),
      const UnicodeEmoji("🙅🏿"),
      const UnicodeEmoji("🙅‍♀️"),
      const UnicodeEmoji("🙅🏻‍♀️"),
      const UnicodeEmoji("🙅🏼‍♀️"),
      const UnicodeEmoji("🙅🏽‍♀️"),
      const UnicodeEmoji("🙅🏾‍♀️"),
      const UnicodeEmoji("🙅🏿‍♀️"),
      const UnicodeEmoji("🙅‍♂️"),
      const UnicodeEmoji("🙅🏻‍♂️"),
      const UnicodeEmoji("🙅🏼‍♂️"),
      const UnicodeEmoji("🙅🏽‍♂️"),
      const UnicodeEmoji("🙅🏾‍♂️"),
      const UnicodeEmoji("🙅🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🤷"), [
      const UnicodeEmoji("🤷"),
      const UnicodeEmoji("🤷🏻"),
      const UnicodeEmoji("🤷🏼"),
      const UnicodeEmoji("🤷🏽"),
      const UnicodeEmoji("🤷🏾"),
      const UnicodeEmoji("🤷🏿"),
      const UnicodeEmoji("🤷‍♀️"),
      const UnicodeEmoji("🤷🏻‍♀️"),
      const UnicodeEmoji("🤷🏼‍♀️"),
      const UnicodeEmoji("🤷🏽‍♀️"),
      const UnicodeEmoji("🤷🏾‍♀️"),
      const UnicodeEmoji("🤷🏿‍♀️"),
      const UnicodeEmoji("🤷‍♂️"),
      const UnicodeEmoji("🤷🏻‍♂️"),
      const UnicodeEmoji("🤷🏼‍♂️"),
      const UnicodeEmoji("🤷🏽‍♂️"),
      const UnicodeEmoji("🤷🏾‍♂️"),
      const UnicodeEmoji("🤷🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🤦"), [
      const UnicodeEmoji("🤦"),
      const UnicodeEmoji("🤦🏻"),
      const UnicodeEmoji("🤦🏼"),
      const UnicodeEmoji("🤦🏽"),
      const UnicodeEmoji("🤦🏾"),
      const UnicodeEmoji("🤦🏿"),
      const UnicodeEmoji("🤦‍♀️"),
      const UnicodeEmoji("🤦🏻‍♀️"),
      const UnicodeEmoji("🤦🏼‍♀️"),
      const UnicodeEmoji("🤦🏽‍♀️"),
      const UnicodeEmoji("🤦🏾‍♀️"),
      const UnicodeEmoji("🤦🏿‍♀️"),
      const UnicodeEmoji("🤦‍♂️"),
      const UnicodeEmoji("🤦🏻‍♂️"),
      const UnicodeEmoji("🤦🏼‍♂️"),
      const UnicodeEmoji("🤦🏽‍♂️"),
      const UnicodeEmoji("🤦🏾‍♂️"),
      const UnicodeEmoji("🤦🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🙍"), [
      const UnicodeEmoji("🙍"),
      const UnicodeEmoji("🙍🏻"),
      const UnicodeEmoji("🙍🏼"),
      const UnicodeEmoji("🙍🏽"),
      const UnicodeEmoji("🙍🏾"),
      const UnicodeEmoji("🙍🏿"),
      const UnicodeEmoji("🙍‍♀️"),
      const UnicodeEmoji("🙍🏻‍♀️"),
      const UnicodeEmoji("🙍🏼‍♀️"),
      const UnicodeEmoji("🙍🏽‍♀️"),
      const UnicodeEmoji("🙍🏾‍♀️"),
      const UnicodeEmoji("🙍🏿‍♀️"),
      const UnicodeEmoji("🙍‍♂️"),
      const UnicodeEmoji("🙍🏻‍♂️"),
      const UnicodeEmoji("🙍🏼‍♂️"),
      const UnicodeEmoji("🙍🏽‍♂️"),
      const UnicodeEmoji("🙍🏾‍♂️"),
      const UnicodeEmoji("🙍🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🙎"), [
      const UnicodeEmoji("🙎"),
      const UnicodeEmoji("🙎🏻"),
      const UnicodeEmoji("🙎🏼"),
      const UnicodeEmoji("🙎🏽"),
      const UnicodeEmoji("🙎🏾"),
      const UnicodeEmoji("🙎🏿"),
      const UnicodeEmoji("🙎‍♀️"),
      const UnicodeEmoji("🙎🏻‍♀️"),
      const UnicodeEmoji("🙎🏼‍♀️"),
      const UnicodeEmoji("🙎🏽‍♀️"),
      const UnicodeEmoji("🙎🏾‍♀️"),
      const UnicodeEmoji("🙎🏿‍♀️"),
      const UnicodeEmoji("🙎‍♂️"),
      const UnicodeEmoji("🙎🏻‍♂️"),
      const UnicodeEmoji("🙎🏼‍♂️"),
      const UnicodeEmoji("🙎🏽‍♂️"),
      const UnicodeEmoji("🙎🏾‍♂️"),
      const UnicodeEmoji("🙎🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧏"), [
      const UnicodeEmoji("🧏"),
      const UnicodeEmoji("🧏🏻"),
      const UnicodeEmoji("🧏🏼"),
      const UnicodeEmoji("🧏🏽"),
      const UnicodeEmoji("🧏🏾"),
      const UnicodeEmoji("🧏🏿"),
      const UnicodeEmoji("🧏‍♀️"),
      const UnicodeEmoji("🧏🏻‍♀️"),
      const UnicodeEmoji("🧏🏼‍♀️"),
      const UnicodeEmoji("🧏🏽‍♀️"),
      const UnicodeEmoji("🧏🏾‍♀️"),
      const UnicodeEmoji("🧏🏿‍♀️"),
      const UnicodeEmoji("🧏‍♂️"),
      const UnicodeEmoji("🧏🏻‍♂️"),
      const UnicodeEmoji("🧏🏼‍♂️"),
      const UnicodeEmoji("🧏🏽‍♂️"),
      const UnicodeEmoji("🧏🏾‍♂️"),
      const UnicodeEmoji("🧏🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("💆"), [
      const UnicodeEmoji("💆"),
      const UnicodeEmoji("💆🏻"),
      const UnicodeEmoji("💆🏼"),
      const UnicodeEmoji("💆🏽"),
      const UnicodeEmoji("💆🏾"),
      const UnicodeEmoji("💆🏿"),
      const UnicodeEmoji("💆‍♀️"),
      const UnicodeEmoji("💆🏻‍♀️"),
      const UnicodeEmoji("💆🏼‍♀️"),
      const UnicodeEmoji("💆🏽‍♀️"),
      const UnicodeEmoji("💆🏾‍♀️"),
      const UnicodeEmoji("💆🏿‍♀️"),
      const UnicodeEmoji("💆‍♂️"),
      const UnicodeEmoji("💆🏻‍♂️"),
      const UnicodeEmoji("💆🏼‍♂️"),
      const UnicodeEmoji("💆🏽‍♂️"),
      const UnicodeEmoji("💆🏾‍♂️"),
      const UnicodeEmoji("💆🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("💇"), [
      const UnicodeEmoji("💇"),
      const UnicodeEmoji("💇🏻"),
      const UnicodeEmoji("💇🏼"),
      const UnicodeEmoji("💇🏽"),
      const UnicodeEmoji("💇🏾"),
      const UnicodeEmoji("💇🏿"),
      const UnicodeEmoji("💇‍♀️"),
      const UnicodeEmoji("💇🏻‍♀️"),
      const UnicodeEmoji("💇🏼‍♀️"),
      const UnicodeEmoji("💇🏽‍♀️"),
      const UnicodeEmoji("💇🏾‍♀️"),
      const UnicodeEmoji("💇🏿‍♀️"),
      const UnicodeEmoji("💇‍♂️"),
      const UnicodeEmoji("💇🏻‍♂️"),
      const UnicodeEmoji("💇🏼‍♂️"),
      const UnicodeEmoji("💇🏽‍♂️"),
      const UnicodeEmoji("💇🏾‍♂️"),
      const UnicodeEmoji("💇🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧖"), [
      const UnicodeEmoji("🧖"),
      const UnicodeEmoji("🧖🏻"),
      const UnicodeEmoji("🧖🏼"),
      const UnicodeEmoji("🧖🏽"),
      const UnicodeEmoji("🧖🏾"),
      const UnicodeEmoji("🧖🏿"),
      const UnicodeEmoji("🧖‍♀️"),
      const UnicodeEmoji("🧖🏻‍♀️"),
      const UnicodeEmoji("🧖🏼‍♀️"),
      const UnicodeEmoji("🧖🏽‍♀️"),
      const UnicodeEmoji("🧖🏾‍♀️"),
      const UnicodeEmoji("🧖🏿‍♀️"),
      const UnicodeEmoji("🧖‍♂️"),
      const UnicodeEmoji("🧖🏻‍♂️"),
      const UnicodeEmoji("🧖🏼‍♂️"),
      const UnicodeEmoji("🧖🏽‍♂️"),
      const UnicodeEmoji("🧖🏾‍♂️"),
      const UnicodeEmoji("🧖🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🛀"), [
      const UnicodeEmoji("🛀"),
      const UnicodeEmoji("🛀🏻"),
      const UnicodeEmoji("🛀🏼"),
      const UnicodeEmoji("🛀🏽"),
      const UnicodeEmoji("🛀🏾"),
      const UnicodeEmoji("🛀🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🛌"), [
      const UnicodeEmoji("🛌"),
      const UnicodeEmoji("🛌🏻"),
      const UnicodeEmoji("🛌🏼"),
      const UnicodeEmoji("🛌🏽"),
      const UnicodeEmoji("🛌🏾"),
      const UnicodeEmoji("🛌🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧘"), [
      const UnicodeEmoji("🧘"),
      const UnicodeEmoji("🧘🏻"),
      const UnicodeEmoji("🧘🏼"),
      const UnicodeEmoji("🧘🏽"),
      const UnicodeEmoji("🧘🏾"),
      const UnicodeEmoji("🧘🏿"),
      const UnicodeEmoji("🧘‍♀️"),
      const UnicodeEmoji("🧘🏻‍♀️"),
      const UnicodeEmoji("🧘🏼‍♀️"),
      const UnicodeEmoji("🧘🏽‍♀️"),
      const UnicodeEmoji("🧘🏾‍♀️"),
      const UnicodeEmoji("🧘🏿‍♀️"),
      const UnicodeEmoji("🧘‍♂️"),
      const UnicodeEmoji("🧘🏻‍♂️"),
      const UnicodeEmoji("🧘🏼‍♂️"),
      const UnicodeEmoji("🧘🏽‍♂️"),
      const UnicodeEmoji("🧘🏾‍♂️"),
      const UnicodeEmoji("🧘🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🦯"), [
      const UnicodeEmoji("🧑‍🦯"),
      const UnicodeEmoji("🧑🏻‍🦯"),
      const UnicodeEmoji("🧑🏼‍🦯"),
      const UnicodeEmoji("🧑🏽‍🦯"),
      const UnicodeEmoji("🧑🏾‍🦯"),
      const UnicodeEmoji("🧑🏿‍🦯"),
      const UnicodeEmoji("👩‍🦯"),
      const UnicodeEmoji("👩🏻‍🦯"),
      const UnicodeEmoji("👩🏼‍🦯"),
      const UnicodeEmoji("👩🏽‍🦯"),
      const UnicodeEmoji("👩🏾‍🦯"),
      const UnicodeEmoji("👩🏿‍🦯"),
      const UnicodeEmoji("👨‍🦯"),
      const UnicodeEmoji("👨🏻‍🦯"),
      const UnicodeEmoji("👨🏼‍🦯"),
      const UnicodeEmoji("👨🏽‍🦯"),
      const UnicodeEmoji("👨🏾‍🦯"),
      const UnicodeEmoji("👨🏿‍🦯"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🦼"), [
      const UnicodeEmoji("🧑‍🦼"),
      const UnicodeEmoji("🧑🏻‍🦼"),
      const UnicodeEmoji("🧑🏼‍🦼"),
      const UnicodeEmoji("🧑🏽‍🦼"),
      const UnicodeEmoji("🧑🏾‍🦼"),
      const UnicodeEmoji("🧑🏿‍🦼"),
      const UnicodeEmoji("👩‍🦼"),
      const UnicodeEmoji("👩🏻‍🦼"),
      const UnicodeEmoji("👩🏼‍🦼"),
      const UnicodeEmoji("👩🏽‍🦼"),
      const UnicodeEmoji("👩🏾‍🦼"),
      const UnicodeEmoji("👩🏿‍🦼"),
      const UnicodeEmoji("👨‍🦼"),
      const UnicodeEmoji("👨🏻‍🦼"),
      const UnicodeEmoji("👨🏼‍🦼"),
      const UnicodeEmoji("👨🏽‍🦼"),
      const UnicodeEmoji("👨🏾‍🦼"),
      const UnicodeEmoji("👨🏿‍🦼"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🦽"), [
      const UnicodeEmoji("🧑‍🦽"),
      const UnicodeEmoji("🧑🏻‍🦽"),
      const UnicodeEmoji("🧑🏼‍🦽"),
      const UnicodeEmoji("🧑🏽‍🦽"),
      const UnicodeEmoji("🧑🏾‍🦽"),
      const UnicodeEmoji("🧑🏿‍🦽"),
      const UnicodeEmoji("👩‍🦽"),
      const UnicodeEmoji("👩🏻‍🦽"),
      const UnicodeEmoji("👩🏼‍🦽"),
      const UnicodeEmoji("👩🏽‍🦽"),
      const UnicodeEmoji("👩🏾‍🦽"),
      const UnicodeEmoji("👩🏿‍🦽"),
      const UnicodeEmoji("👨‍🦽"),
      const UnicodeEmoji("👨🏻‍🦽"),
      const UnicodeEmoji("👨🏼‍🦽"),
      const UnicodeEmoji("👨🏽‍🦽"),
      const UnicodeEmoji("👨🏾‍🦽"),
      const UnicodeEmoji("👨🏿‍🦽"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧎"), [
      const UnicodeEmoji("🧎"),
      const UnicodeEmoji("🧎🏻"),
      const UnicodeEmoji("🧎🏼"),
      const UnicodeEmoji("🧎🏽"),
      const UnicodeEmoji("🧎🏾"),
      const UnicodeEmoji("🧎🏿"),
      const UnicodeEmoji("🧎‍♀️"),
      const UnicodeEmoji("🧎🏻‍♀️"),
      const UnicodeEmoji("🧎🏼‍♀️"),
      const UnicodeEmoji("🧎🏽‍♀️"),
      const UnicodeEmoji("🧎🏾‍♀️"),
      const UnicodeEmoji("🧎🏿‍♀️"),
      const UnicodeEmoji("🧎‍♂️"),
      const UnicodeEmoji("🧎🏻‍♂️"),
      const UnicodeEmoji("🧎🏼‍♂️"),
      const UnicodeEmoji("🧎🏽‍♂️"),
      const UnicodeEmoji("🧎🏾‍♂️"),
      const UnicodeEmoji("🧎🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧍"), [
      const UnicodeEmoji("🧍"),
      const UnicodeEmoji("🧍🏻"),
      const UnicodeEmoji("🧍🏼"),
      const UnicodeEmoji("🧍🏽"),
      const UnicodeEmoji("🧍🏾"),
      const UnicodeEmoji("🧍🏿"),
      const UnicodeEmoji("🧍‍♀️"),
      const UnicodeEmoji("🧍🏻‍♀️"),
      const UnicodeEmoji("🧍🏼‍♀️"),
      const UnicodeEmoji("🧍🏽‍♀️"),
      const UnicodeEmoji("🧍🏾‍♀️"),
      const UnicodeEmoji("🧍🏿‍♀️"),
      const UnicodeEmoji("🧍‍♂️"),
      const UnicodeEmoji("🧍🏻‍♂️"),
      const UnicodeEmoji("🧍🏼‍♂️"),
      const UnicodeEmoji("🧍🏽‍♂️"),
      const UnicodeEmoji("🧍🏾‍♂️"),
      const UnicodeEmoji("🧍🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🚶"), [
      const UnicodeEmoji("🚶"),
      const UnicodeEmoji("🚶🏻"),
      const UnicodeEmoji("🚶🏼"),
      const UnicodeEmoji("🚶🏽"),
      const UnicodeEmoji("🚶🏾"),
      const UnicodeEmoji("🚶🏿"),
      const UnicodeEmoji("🚶‍♀️"),
      const UnicodeEmoji("🚶🏻‍♀️"),
      const UnicodeEmoji("🚶🏼‍♀️"),
      const UnicodeEmoji("🚶🏽‍♀️"),
      const UnicodeEmoji("🚶🏾‍♀️"),
      const UnicodeEmoji("🚶🏿‍♀️"),
      const UnicodeEmoji("🚶‍♂️"),
      const UnicodeEmoji("🚶🏻‍♂️"),
      const UnicodeEmoji("🚶🏼‍♂️"),
      const UnicodeEmoji("🚶🏽‍♂️"),
      const UnicodeEmoji("🚶🏾‍♂️"),
      const UnicodeEmoji("🚶🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🏃"), [
      const UnicodeEmoji("🏃"),
      const UnicodeEmoji("🏃🏻"),
      const UnicodeEmoji("🏃🏼"),
      const UnicodeEmoji("🏃🏽"),
      const UnicodeEmoji("🏃🏾"),
      const UnicodeEmoji("🏃🏿"),
      const UnicodeEmoji("🏃‍♀️"),
      const UnicodeEmoji("🏃🏻‍♀️"),
      const UnicodeEmoji("🏃🏼‍♀️"),
      const UnicodeEmoji("🏃🏽‍♀️"),
      const UnicodeEmoji("🏃🏾‍♀️"),
      const UnicodeEmoji("🏃🏿‍♀️"),
      const UnicodeEmoji("🏃‍♂️"),
      const UnicodeEmoji("🏃🏻‍♂️"),
      const UnicodeEmoji("🏃🏼‍♂️"),
      const UnicodeEmoji("🏃🏽‍♂️"),
      const UnicodeEmoji("🏃🏾‍♂️"),
      const UnicodeEmoji("🏃🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🤸"), [
      const UnicodeEmoji("🤸"),
      const UnicodeEmoji("🤸🏻"),
      const UnicodeEmoji("🤸🏼"),
      const UnicodeEmoji("🤸🏽"),
      const UnicodeEmoji("🤸🏾"),
      const UnicodeEmoji("🤸🏿"),
      const UnicodeEmoji("🤸‍♀️"),
      const UnicodeEmoji("🤸🏻‍♀️"),
      const UnicodeEmoji("🤸🏼‍♀️"),
      const UnicodeEmoji("🤸🏽‍♀️"),
      const UnicodeEmoji("🤸🏾‍♀️"),
      const UnicodeEmoji("🤸🏿‍♀️"),
      const UnicodeEmoji("🤸‍♂️"),
      const UnicodeEmoji("🤸🏻‍♂️"),
      const UnicodeEmoji("🤸🏼‍♂️"),
      const UnicodeEmoji("🤸🏽‍♂️"),
      const UnicodeEmoji("🤸🏾‍♂️"),
      const UnicodeEmoji("🤸🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🏋️"), [
      const UnicodeEmoji("🏋️"),
      const UnicodeEmoji("🏋🏻"),
      const UnicodeEmoji("🏋🏼"),
      const UnicodeEmoji("🏋🏽"),
      const UnicodeEmoji("🏋🏾"),
      const UnicodeEmoji("🏋🏿"),
      const UnicodeEmoji("🏋️‍♀️"),
      const UnicodeEmoji("🏋🏻‍♀️"),
      const UnicodeEmoji("🏋🏼‍♀️"),
      const UnicodeEmoji("🏋🏽‍♀️"),
      const UnicodeEmoji("🏋🏾‍♀️"),
      const UnicodeEmoji("🏋🏿‍♀️"),
      const UnicodeEmoji("🏋️‍♂️"),
      const UnicodeEmoji("🏋🏻‍♂️"),
      const UnicodeEmoji("🏋🏼‍♂️"),
      const UnicodeEmoji("🏋🏽‍♂️"),
      const UnicodeEmoji("🏋🏾‍♂️"),
      const UnicodeEmoji("🏋🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("⛹️"), [
      const UnicodeEmoji("⛹️"),
      const UnicodeEmoji("⛹🏻"),
      const UnicodeEmoji("⛹🏼"),
      const UnicodeEmoji("⛹🏽"),
      const UnicodeEmoji("⛹🏾"),
      const UnicodeEmoji("⛹🏿"),
      const UnicodeEmoji("⛹️‍♀️"),
      const UnicodeEmoji("⛹🏻‍♀️"),
      const UnicodeEmoji("⛹🏼‍♀️"),
      const UnicodeEmoji("⛹🏽‍♀️"),
      const UnicodeEmoji("⛹🏾‍♀️"),
      const UnicodeEmoji("⛹🏿‍♀️"),
      const UnicodeEmoji("⛹️‍♂️"),
      const UnicodeEmoji("⛹🏻‍♂️"),
      const UnicodeEmoji("⛹🏼‍♂️"),
      const UnicodeEmoji("⛹🏽‍♂️"),
      const UnicodeEmoji("⛹🏾‍♂️"),
      const UnicodeEmoji("⛹🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🤾"), [
      const UnicodeEmoji("🤾"),
      const UnicodeEmoji("🤾🏻"),
      const UnicodeEmoji("🤾🏼"),
      const UnicodeEmoji("🤾🏽"),
      const UnicodeEmoji("🤾🏾"),
      const UnicodeEmoji("🤾🏿"),
      const UnicodeEmoji("🤾‍♀️"),
      const UnicodeEmoji("🤾🏻‍♀️"),
      const UnicodeEmoji("🤾🏼‍♀️"),
      const UnicodeEmoji("🤾🏽‍♀️"),
      const UnicodeEmoji("🤾🏾‍♀️"),
      const UnicodeEmoji("🤾🏿‍♀️"),
      const UnicodeEmoji("🤾‍♂️"),
      const UnicodeEmoji("🤾🏻‍♂️"),
      const UnicodeEmoji("🤾🏼‍♂️"),
      const UnicodeEmoji("🤾🏽‍♂️"),
      const UnicodeEmoji("🤾🏾‍♂️"),
      const UnicodeEmoji("🤾🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🚴"), [
      const UnicodeEmoji("🚴"),
      const UnicodeEmoji("🚴🏻"),
      const UnicodeEmoji("🚴🏼"),
      const UnicodeEmoji("🚴🏽"),
      const UnicodeEmoji("🚴🏾"),
      const UnicodeEmoji("🚴🏿"),
      const UnicodeEmoji("🚴‍♀️"),
      const UnicodeEmoji("🚴🏻‍♀️"),
      const UnicodeEmoji("🚴🏼‍♀️"),
      const UnicodeEmoji("🚴🏽‍♀️"),
      const UnicodeEmoji("🚴🏾‍♀️"),
      const UnicodeEmoji("🚴🏿‍♀️"),
      const UnicodeEmoji("🚴‍♂️"),
      const UnicodeEmoji("🚴🏻‍♂️"),
      const UnicodeEmoji("🚴🏼‍♂️"),
      const UnicodeEmoji("🚴🏽‍♂️"),
      const UnicodeEmoji("🚴🏾‍♂️"),
      const UnicodeEmoji("🚴🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🚵"), [
      const UnicodeEmoji("🚵"),
      const UnicodeEmoji("🚵🏻"),
      const UnicodeEmoji("🚵🏼"),
      const UnicodeEmoji("🚵🏽"),
      const UnicodeEmoji("🚵🏾"),
      const UnicodeEmoji("🚵🏿"),
      const UnicodeEmoji("🚵‍♀️"),
      const UnicodeEmoji("🚵🏻‍♀️"),
      const UnicodeEmoji("🚵🏼‍♀️"),
      const UnicodeEmoji("🚵🏽‍♀️"),
      const UnicodeEmoji("🚵🏾‍♀️"),
      const UnicodeEmoji("🚵🏿‍♀️"),
      const UnicodeEmoji("🚵‍♂️"),
      const UnicodeEmoji("🚵🏻‍♂️"),
      const UnicodeEmoji("🚵🏼‍♂️"),
      const UnicodeEmoji("🚵🏽‍♂️"),
      const UnicodeEmoji("🚵🏾‍♂️"),
      const UnicodeEmoji("🚵🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧗"), [
      const UnicodeEmoji("🧗"),
      const UnicodeEmoji("🧗🏻"),
      const UnicodeEmoji("🧗🏼"),
      const UnicodeEmoji("🧗🏽"),
      const UnicodeEmoji("🧗🏾"),
      const UnicodeEmoji("🧗🏿"),
      const UnicodeEmoji("🧗‍♀️"),
      const UnicodeEmoji("🧗🏻‍♀️"),
      const UnicodeEmoji("🧗🏼‍♀️"),
      const UnicodeEmoji("🧗🏽‍♀️"),
      const UnicodeEmoji("🧗🏾‍♀️"),
      const UnicodeEmoji("🧗🏿‍♀️"),
      const UnicodeEmoji("🧗‍♂️"),
      const UnicodeEmoji("🧗🏻‍♂️"),
      const UnicodeEmoji("🧗🏼‍♂️"),
      const UnicodeEmoji("🧗🏽‍♂️"),
      const UnicodeEmoji("🧗🏾‍♂️"),
      const UnicodeEmoji("🧗🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🤼"), [
      const UnicodeEmoji("🤼"),
      const UnicodeEmoji("🤼‍♀️"),
      const UnicodeEmoji("🤼‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🤹"), [
      const UnicodeEmoji("🤹"),
      const UnicodeEmoji("🤹🏻"),
      const UnicodeEmoji("🤹🏼"),
      const UnicodeEmoji("🤹🏽"),
      const UnicodeEmoji("🤹🏾"),
      const UnicodeEmoji("🤹🏿"),
      const UnicodeEmoji("🤹‍♀️"),
      const UnicodeEmoji("🤹🏻‍♀️"),
      const UnicodeEmoji("🤹🏼‍♀️"),
      const UnicodeEmoji("🤹🏽‍♀️"),
      const UnicodeEmoji("🤹🏾‍♀️"),
      const UnicodeEmoji("🤹🏿‍♀️"),
      const UnicodeEmoji("🤹‍♂️"),
      const UnicodeEmoji("🤹🏻‍♂️"),
      const UnicodeEmoji("🤹🏼‍♂️"),
      const UnicodeEmoji("🤹🏽‍♂️"),
      const UnicodeEmoji("🤹🏾‍♂️"),
      const UnicodeEmoji("🤹🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🏌️"), [
      const UnicodeEmoji("🏌️"),
      const UnicodeEmoji("🏌🏻"),
      const UnicodeEmoji("🏌🏼"),
      const UnicodeEmoji("🏌🏽"),
      const UnicodeEmoji("🏌🏾"),
      const UnicodeEmoji("🏌🏿"),
      const UnicodeEmoji("🏌️‍♀️"),
      const UnicodeEmoji("🏌🏻‍♀️"),
      const UnicodeEmoji("🏌🏼‍♀️"),
      const UnicodeEmoji("🏌🏽‍♀️"),
      const UnicodeEmoji("🏌🏾‍♀️"),
      const UnicodeEmoji("🏌🏿‍♀️"),
      const UnicodeEmoji("🏌️‍♂️"),
      const UnicodeEmoji("🏌🏻‍♂️"),
      const UnicodeEmoji("🏌🏼‍♂️"),
      const UnicodeEmoji("🏌🏽‍♂️"),
      const UnicodeEmoji("🏌🏾‍♂️"),
      const UnicodeEmoji("🏌🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🏇"), [
      const UnicodeEmoji("🏇"),
      const UnicodeEmoji("🏇🏻"),
      const UnicodeEmoji("🏇🏼"),
      const UnicodeEmoji("🏇🏽"),
      const UnicodeEmoji("🏇🏾"),
      const UnicodeEmoji("🏇🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🤺"),
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("⛷️"),
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🏂"), [
      const UnicodeEmoji("🏂"),
      const UnicodeEmoji("🏂🏻"),
      const UnicodeEmoji("🏂🏼"),
      const UnicodeEmoji("🏂🏽"),
      const UnicodeEmoji("🏂🏾"),
      const UnicodeEmoji("🏂🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🪂"),
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🏄"), [
      const UnicodeEmoji("🏄"),
      const UnicodeEmoji("🏄🏻"),
      const UnicodeEmoji("🏄🏼"),
      const UnicodeEmoji("🏄🏽"),
      const UnicodeEmoji("🏄🏾"),
      const UnicodeEmoji("🏄🏿"),
      const UnicodeEmoji("🏄‍♀️"),
      const UnicodeEmoji("🏄🏻‍♀️"),
      const UnicodeEmoji("🏄🏼‍♀️"),
      const UnicodeEmoji("🏄🏽‍♀️"),
      const UnicodeEmoji("🏄🏾‍♀️"),
      const UnicodeEmoji("🏄🏿‍♀️"),
      const UnicodeEmoji("🏄‍♂️"),
      const UnicodeEmoji("🏄🏻‍♂️"),
      const UnicodeEmoji("🏄🏼‍♂️"),
      const UnicodeEmoji("🏄🏽‍♂️"),
      const UnicodeEmoji("🏄🏾‍♂️"),
      const UnicodeEmoji("🏄🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🚣"), [
      const UnicodeEmoji("🚣"),
      const UnicodeEmoji("🚣🏻"),
      const UnicodeEmoji("🚣🏼"),
      const UnicodeEmoji("🚣🏽"),
      const UnicodeEmoji("🚣🏾"),
      const UnicodeEmoji("🚣🏿"),
      const UnicodeEmoji("🚣‍♀️"),
      const UnicodeEmoji("🚣🏻‍♀️"),
      const UnicodeEmoji("🚣🏼‍♀️"),
      const UnicodeEmoji("🚣🏽‍♀️"),
      const UnicodeEmoji("🚣🏾‍♀️"),
      const UnicodeEmoji("🚣🏿‍♀️"),
      const UnicodeEmoji("🚣‍♂️"),
      const UnicodeEmoji("🚣🏻‍♂️"),
      const UnicodeEmoji("🚣🏼‍♂️"),
      const UnicodeEmoji("🚣🏽‍♂️"),
      const UnicodeEmoji("🚣🏾‍♂️"),
      const UnicodeEmoji("🚣🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🏊"), [
      const UnicodeEmoji("🏊"),
      const UnicodeEmoji("🏊🏻"),
      const UnicodeEmoji("🏊🏼"),
      const UnicodeEmoji("🏊🏽"),
      const UnicodeEmoji("🏊🏾"),
      const UnicodeEmoji("🏊🏿"),
      const UnicodeEmoji("🏊‍♀️"),
      const UnicodeEmoji("🏊🏻‍♀️"),
      const UnicodeEmoji("🏊🏼‍♀️"),
      const UnicodeEmoji("🏊🏽‍♀️"),
      const UnicodeEmoji("🏊🏾‍♀️"),
      const UnicodeEmoji("🏊🏿‍♀️"),
      const UnicodeEmoji("🏊‍♂️"),
      const UnicodeEmoji("🏊🏻‍♂️"),
      const UnicodeEmoji("🏊🏼‍♂️"),
      const UnicodeEmoji("🏊🏽‍♂️"),
      const UnicodeEmoji("🏊🏾‍♂️"),
      const UnicodeEmoji("🏊🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🤽"), [
      const UnicodeEmoji("🤽"),
      const UnicodeEmoji("🤽🏻"),
      const UnicodeEmoji("🤽🏼"),
      const UnicodeEmoji("🤽🏽"),
      const UnicodeEmoji("🤽🏾"),
      const UnicodeEmoji("🤽🏿"),
      const UnicodeEmoji("🤽‍♀️"),
      const UnicodeEmoji("🤽🏻‍♀️"),
      const UnicodeEmoji("🤽🏼‍♀️"),
      const UnicodeEmoji("🤽🏽‍♀️"),
      const UnicodeEmoji("🤽🏾‍♀️"),
      const UnicodeEmoji("🤽🏿‍♀️"),
      const UnicodeEmoji("🤽‍♂️"),
      const UnicodeEmoji("🤽🏻‍♂️"),
      const UnicodeEmoji("🤽🏼‍♂️"),
      const UnicodeEmoji("🤽🏽‍♂️"),
      const UnicodeEmoji("🤽🏾‍♂️"),
      const UnicodeEmoji("🤽🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧜"), [
      const UnicodeEmoji("🧜"),
      const UnicodeEmoji("🧜🏻"),
      const UnicodeEmoji("🧜🏼"),
      const UnicodeEmoji("🧜🏽"),
      const UnicodeEmoji("🧜🏾"),
      const UnicodeEmoji("🧜🏿"),
      const UnicodeEmoji("🧜‍♀️"),
      const UnicodeEmoji("🧜🏻‍♀️"),
      const UnicodeEmoji("🧜🏼‍♀️"),
      const UnicodeEmoji("🧜🏽‍♀️"),
      const UnicodeEmoji("🧜🏾‍♀️"),
      const UnicodeEmoji("🧜🏿‍♀️"),
      const UnicodeEmoji("🧜‍♂️"),
      const UnicodeEmoji("🧜🏻‍♂️"),
      const UnicodeEmoji("🧜🏼‍♂️"),
      const UnicodeEmoji("🧜🏽‍♂️"),
      const UnicodeEmoji("🧜🏾‍♂️"),
      const UnicodeEmoji("🧜🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧚"), [
      const UnicodeEmoji("🧚"),
      const UnicodeEmoji("🧚🏻"),
      const UnicodeEmoji("🧚🏼"),
      const UnicodeEmoji("🧚🏽"),
      const UnicodeEmoji("🧚🏾"),
      const UnicodeEmoji("🧚🏿"),
      const UnicodeEmoji("🧚‍♀️"),
      const UnicodeEmoji("🧚🏻‍♀️"),
      const UnicodeEmoji("🧚🏼‍♀️"),
      const UnicodeEmoji("🧚🏽‍♀️"),
      const UnicodeEmoji("🧚🏾‍♀️"),
      const UnicodeEmoji("🧚🏿‍♀️"),
      const UnicodeEmoji("🧚‍♂️"),
      const UnicodeEmoji("🧚🏻‍♂️"),
      const UnicodeEmoji("🧚🏼‍♂️"),
      const UnicodeEmoji("🧚🏽‍♂️"),
      const UnicodeEmoji("🧚🏾‍♂️"),
      const UnicodeEmoji("🧚🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧞"), [
      const UnicodeEmoji("🧞"),
      const UnicodeEmoji("🧞‍♀️"),
      const UnicodeEmoji("🧞‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧝"), [
      const UnicodeEmoji("🧝"),
      const UnicodeEmoji("🧝🏻"),
      const UnicodeEmoji("🧝🏼"),
      const UnicodeEmoji("🧝🏽"),
      const UnicodeEmoji("🧝🏾"),
      const UnicodeEmoji("🧝🏿"),
      const UnicodeEmoji("🧝‍♀️"),
      const UnicodeEmoji("🧝🏻‍♀️"),
      const UnicodeEmoji("🧝🏼‍♀️"),
      const UnicodeEmoji("🧝🏽‍♀️"),
      const UnicodeEmoji("🧝🏾‍♀️"),
      const UnicodeEmoji("🧝🏿‍♀️"),
      const UnicodeEmoji("🧝‍♂️"),
      const UnicodeEmoji("🧝🏻‍♂️"),
      const UnicodeEmoji("🧝🏼‍♂️"),
      const UnicodeEmoji("🧝🏽‍♂️"),
      const UnicodeEmoji("🧝🏾‍♂️"),
      const UnicodeEmoji("🧝🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧙"), [
      const UnicodeEmoji("🧙"),
      const UnicodeEmoji("🧙🏻"),
      const UnicodeEmoji("🧙🏼"),
      const UnicodeEmoji("🧙🏽"),
      const UnicodeEmoji("🧙🏾"),
      const UnicodeEmoji("🧙🏿"),
      const UnicodeEmoji("🧙‍♀️"),
      const UnicodeEmoji("🧙🏻‍♀️"),
      const UnicodeEmoji("🧙🏼‍♀️"),
      const UnicodeEmoji("🧙🏽‍♀️"),
      const UnicodeEmoji("🧙🏾‍♀️"),
      const UnicodeEmoji("🧙🏿‍♀️"),
      const UnicodeEmoji("🧙‍♂️"),
      const UnicodeEmoji("🧙🏻‍♂️"),
      const UnicodeEmoji("🧙🏼‍♂️"),
      const UnicodeEmoji("🧙🏽‍♂️"),
      const UnicodeEmoji("🧙🏾‍♂️"),
      const UnicodeEmoji("🧙🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧛"), [
      const UnicodeEmoji("🧛"),
      const UnicodeEmoji("🧛🏻"),
      const UnicodeEmoji("🧛🏼"),
      const UnicodeEmoji("🧛🏽"),
      const UnicodeEmoji("🧛🏾"),
      const UnicodeEmoji("🧛🏿"),
      const UnicodeEmoji("🧛‍♀️"),
      const UnicodeEmoji("🧛🏻‍♀️"),
      const UnicodeEmoji("🧛🏼‍♀️"),
      const UnicodeEmoji("🧛🏽‍♀️"),
      const UnicodeEmoji("🧛🏾‍♀️"),
      const UnicodeEmoji("🧛🏿‍♀️"),
      const UnicodeEmoji("🧛‍♂️"),
      const UnicodeEmoji("🧛🏻‍♂️"),
      const UnicodeEmoji("🧛🏼‍♂️"),
      const UnicodeEmoji("🧛🏽‍♂️"),
      const UnicodeEmoji("🧛🏾‍♂️"),
      const UnicodeEmoji("🧛🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧟"), [
      const UnicodeEmoji("🧟"),
      const UnicodeEmoji("🧟‍♀️"),
      const UnicodeEmoji("🧟‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧌"),
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🦸"), [
      const UnicodeEmoji("🦸"),
      const UnicodeEmoji("🦸🏻"),
      const UnicodeEmoji("🦸🏼"),
      const UnicodeEmoji("🦸🏽"),
      const UnicodeEmoji("🦸🏾"),
      const UnicodeEmoji("🦸🏿"),
      const UnicodeEmoji("🦸‍♀️"),
      const UnicodeEmoji("🦸🏻‍♀️"),
      const UnicodeEmoji("🦸🏼‍♀️"),
      const UnicodeEmoji("🦸🏽‍♀️"),
      const UnicodeEmoji("🦸🏾‍♀️"),
      const UnicodeEmoji("🦸🏿‍♀️"),
      const UnicodeEmoji("🦸‍♂️"),
      const UnicodeEmoji("🦸🏻‍♂️"),
      const UnicodeEmoji("🦸🏼‍♂️"),
      const UnicodeEmoji("🦸🏽‍♂️"),
      const UnicodeEmoji("🦸🏾‍♂️"),
      const UnicodeEmoji("🦸🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🦹"), [
      const UnicodeEmoji("🦹"),
      const UnicodeEmoji("🦹🏻"),
      const UnicodeEmoji("🦹🏼"),
      const UnicodeEmoji("🦹🏽"),
      const UnicodeEmoji("🦹🏾"),
      const UnicodeEmoji("🦹🏿"),
      const UnicodeEmoji("🦹‍♀️"),
      const UnicodeEmoji("🦹🏻‍♀️"),
      const UnicodeEmoji("🦹🏼‍♀️"),
      const UnicodeEmoji("🦹🏽‍♀️"),
      const UnicodeEmoji("🦹🏾‍♀️"),
      const UnicodeEmoji("🦹🏿‍♀️"),
      const UnicodeEmoji("🦹‍♂️"),
      const UnicodeEmoji("🦹🏻‍♂️"),
      const UnicodeEmoji("🦹🏼‍♂️"),
      const UnicodeEmoji("🦹🏽‍♂️"),
      const UnicodeEmoji("🦹🏾‍♂️"),
      const UnicodeEmoji("🦹🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🥷"), [
      const UnicodeEmoji("🥷"),
      const UnicodeEmoji("🥷🏻"),
      const UnicodeEmoji("🥷🏼"),
      const UnicodeEmoji("🥷🏽"),
      const UnicodeEmoji("🥷🏾"),
      const UnicodeEmoji("🥷🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🎄"), [
      const UnicodeEmoji("🧑‍🎄"),
      const UnicodeEmoji("🧑🏻‍🎄"),
      const UnicodeEmoji("🧑🏼‍🎄"),
      const UnicodeEmoji("🧑🏽‍🎄"),
      const UnicodeEmoji("🧑🏾‍🎄"),
      const UnicodeEmoji("🧑🏿‍🎄"),
      const UnicodeEmoji("🤶"),
      const UnicodeEmoji("🤶🏻"),
      const UnicodeEmoji("🤶🏼"),
      const UnicodeEmoji("🤶🏽"),
      const UnicodeEmoji("🤶🏾"),
      const UnicodeEmoji("🤶🏿"),
      const UnicodeEmoji("🎅"),
      const UnicodeEmoji("🎅🏻"),
      const UnicodeEmoji("🎅🏼"),
      const UnicodeEmoji("🎅🏽"),
      const UnicodeEmoji("🎅🏾"),
      const UnicodeEmoji("🎅🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👼"), [
      const UnicodeEmoji("👼"),
      const UnicodeEmoji("👼🏻"),
      const UnicodeEmoji("👼🏼"),
      const UnicodeEmoji("👼🏽"),
      const UnicodeEmoji("👼🏾"),
      const UnicodeEmoji("👼🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("💂"), [
      const UnicodeEmoji("💂"),
      const UnicodeEmoji("💂🏻"),
      const UnicodeEmoji("💂🏼"),
      const UnicodeEmoji("💂🏽"),
      const UnicodeEmoji("💂🏾"),
      const UnicodeEmoji("💂🏿"),
      const UnicodeEmoji("💂‍♀️"),
      const UnicodeEmoji("💂🏻‍♀️"),
      const UnicodeEmoji("💂🏼‍♀️"),
      const UnicodeEmoji("💂🏽‍♀️"),
      const UnicodeEmoji("💂🏾‍♀️"),
      const UnicodeEmoji("💂🏿‍♀️"),
      const UnicodeEmoji("💂‍♂️"),
      const UnicodeEmoji("💂🏻‍♂️"),
      const UnicodeEmoji("💂🏼‍♂️"),
      const UnicodeEmoji("💂🏽‍♂️"),
      const UnicodeEmoji("💂🏾‍♂️"),
      const UnicodeEmoji("💂🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🫅"), [
      const UnicodeEmoji("🫅"),
      const UnicodeEmoji("🫅🏻"),
      const UnicodeEmoji("🫅🏼"),
      const UnicodeEmoji("🫅🏽"),
      const UnicodeEmoji("🫅🏾"),
      const UnicodeEmoji("🫅🏿"),
      const UnicodeEmoji("👸"),
      const UnicodeEmoji("👸🏻"),
      const UnicodeEmoji("👸🏼"),
      const UnicodeEmoji("👸🏽"),
      const UnicodeEmoji("👸🏾"),
      const UnicodeEmoji("👸🏿"),
      const UnicodeEmoji("🤴"),
      const UnicodeEmoji("🤴🏻"),
      const UnicodeEmoji("🤴🏼"),
      const UnicodeEmoji("🤴🏽"),
      const UnicodeEmoji("🤴🏾"),
      const UnicodeEmoji("🤴🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🤵"), [
      const UnicodeEmoji("🤵"),
      const UnicodeEmoji("🤵🏻"),
      const UnicodeEmoji("🤵🏼"),
      const UnicodeEmoji("🤵🏽"),
      const UnicodeEmoji("🤵🏾"),
      const UnicodeEmoji("🤵🏿"),
      const UnicodeEmoji("🤵‍♀️"),
      const UnicodeEmoji("🤵🏻‍♀️"),
      const UnicodeEmoji("🤵🏼‍♀️"),
      const UnicodeEmoji("🤵🏽‍♀️"),
      const UnicodeEmoji("🤵🏾‍♀️"),
      const UnicodeEmoji("🤵🏿‍♀️"),
      const UnicodeEmoji("🤵‍♂️"),
      const UnicodeEmoji("🤵🏻‍♂️"),
      const UnicodeEmoji("🤵🏼‍♂️"),
      const UnicodeEmoji("🤵🏽‍♂️"),
      const UnicodeEmoji("🤵🏾‍♂️"),
      const UnicodeEmoji("🤵🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👰"), [
      const UnicodeEmoji("👰"),
      const UnicodeEmoji("👰🏻"),
      const UnicodeEmoji("👰🏼"),
      const UnicodeEmoji("👰🏽"),
      const UnicodeEmoji("👰🏾"),
      const UnicodeEmoji("👰🏿"),
      const UnicodeEmoji("👰‍♀️"),
      const UnicodeEmoji("👰🏻‍♀️"),
      const UnicodeEmoji("👰🏼‍♀️"),
      const UnicodeEmoji("👰🏽‍♀️"),
      const UnicodeEmoji("👰🏾‍♀️"),
      const UnicodeEmoji("👰🏿‍♀️"),
      const UnicodeEmoji("👰‍♂️"),
      const UnicodeEmoji("👰🏻‍♂️"),
      const UnicodeEmoji("👰🏼‍♂️"),
      const UnicodeEmoji("👰🏽‍♂️"),
      const UnicodeEmoji("👰🏾‍♂️"),
      const UnicodeEmoji("👰🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🚀"), [
      const UnicodeEmoji("🧑‍🚀"),
      const UnicodeEmoji("🧑🏻‍🚀"),
      const UnicodeEmoji("🧑🏼‍🚀"),
      const UnicodeEmoji("🧑🏽‍🚀"),
      const UnicodeEmoji("🧑🏾‍🚀"),
      const UnicodeEmoji("🧑🏿‍🚀"),
      const UnicodeEmoji("👩‍🚀"),
      const UnicodeEmoji("👩🏻‍🚀"),
      const UnicodeEmoji("👩🏼‍🚀"),
      const UnicodeEmoji("👩🏽‍🚀"),
      const UnicodeEmoji("👩🏾‍🚀"),
      const UnicodeEmoji("👩🏿‍🚀"),
      const UnicodeEmoji("👨‍🚀"),
      const UnicodeEmoji("👨🏻‍🚀"),
      const UnicodeEmoji("👨🏼‍🚀"),
      const UnicodeEmoji("👨🏽‍🚀"),
      const UnicodeEmoji("👨🏾‍🚀"),
      const UnicodeEmoji("👨🏿‍🚀"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👷"), [
      const UnicodeEmoji("👷"),
      const UnicodeEmoji("👷🏻"),
      const UnicodeEmoji("👷🏼"),
      const UnicodeEmoji("👷🏽"),
      const UnicodeEmoji("👷🏾"),
      const UnicodeEmoji("👷🏿"),
      const UnicodeEmoji("👷‍♀️"),
      const UnicodeEmoji("👷🏻‍♀️"),
      const UnicodeEmoji("👷🏼‍♀️"),
      const UnicodeEmoji("👷🏽‍♀️"),
      const UnicodeEmoji("👷🏾‍♀️"),
      const UnicodeEmoji("👷🏿‍♀️"),
      const UnicodeEmoji("👷‍♂️"),
      const UnicodeEmoji("👷🏻‍♂️"),
      const UnicodeEmoji("👷🏼‍♂️"),
      const UnicodeEmoji("👷🏽‍♂️"),
      const UnicodeEmoji("👷🏾‍♂️"),
      const UnicodeEmoji("👷🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👮"), [
      const UnicodeEmoji("👮"),
      const UnicodeEmoji("👮🏻"),
      const UnicodeEmoji("👮🏼"),
      const UnicodeEmoji("👮🏽"),
      const UnicodeEmoji("👮🏾"),
      const UnicodeEmoji("👮🏿"),
      const UnicodeEmoji("👮‍♀️"),
      const UnicodeEmoji("👮🏻‍♀️"),
      const UnicodeEmoji("👮🏼‍♀️"),
      const UnicodeEmoji("👮🏽‍♀️"),
      const UnicodeEmoji("👮🏾‍♀️"),
      const UnicodeEmoji("👮🏿‍♀️"),
      const UnicodeEmoji("👮‍♂️"),
      const UnicodeEmoji("👮🏻‍♂️"),
      const UnicodeEmoji("👮🏼‍♂️"),
      const UnicodeEmoji("👮🏽‍♂️"),
      const UnicodeEmoji("👮🏾‍♂️"),
      const UnicodeEmoji("👮🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🕵️"), [
      const UnicodeEmoji("🕵️"),
      const UnicodeEmoji("🕵🏻"),
      const UnicodeEmoji("🕵🏼"),
      const UnicodeEmoji("🕵🏽"),
      const UnicodeEmoji("🕵🏾"),
      const UnicodeEmoji("🕵🏿"),
      const UnicodeEmoji("🕵️‍♀️"),
      const UnicodeEmoji("🕵🏻‍♀️"),
      const UnicodeEmoji("🕵🏼‍♀️"),
      const UnicodeEmoji("🕵🏽‍♀️"),
      const UnicodeEmoji("🕵🏾‍♀️"),
      const UnicodeEmoji("🕵🏿‍♀️"),
      const UnicodeEmoji("🕵️‍♂️"),
      const UnicodeEmoji("🕵🏻‍♂️"),
      const UnicodeEmoji("🕵🏼‍♂️"),
      const UnicodeEmoji("🕵🏽‍♂️"),
      const UnicodeEmoji("🕵🏾‍♂️"),
      const UnicodeEmoji("🕵🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍✈️"), [
      const UnicodeEmoji("🧑‍✈️"),
      const UnicodeEmoji("🧑🏻‍✈️"),
      const UnicodeEmoji("🧑🏼‍✈️"),
      const UnicodeEmoji("🧑🏽‍✈️"),
      const UnicodeEmoji("🧑🏾‍✈️"),
      const UnicodeEmoji("🧑🏿‍✈️"),
      const UnicodeEmoji("👩‍✈️"),
      const UnicodeEmoji("👩🏻‍✈️"),
      const UnicodeEmoji("👩🏼‍✈️"),
      const UnicodeEmoji("👩🏽‍✈️"),
      const UnicodeEmoji("👩🏾‍✈️"),
      const UnicodeEmoji("👩🏿‍✈️"),
      const UnicodeEmoji("👨‍✈️"),
      const UnicodeEmoji("👨🏻‍✈️"),
      const UnicodeEmoji("👨🏼‍✈️"),
      const UnicodeEmoji("👨🏽‍✈️"),
      const UnicodeEmoji("👨🏾‍✈️"),
      const UnicodeEmoji("👨🏿‍✈️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🔬"), [
      const UnicodeEmoji("🧑‍🔬"),
      const UnicodeEmoji("🧑🏻‍🔬"),
      const UnicodeEmoji("🧑🏼‍🔬"),
      const UnicodeEmoji("🧑🏽‍🔬"),
      const UnicodeEmoji("🧑🏾‍🔬"),
      const UnicodeEmoji("🧑🏿‍🔬"),
      const UnicodeEmoji("👩‍🔬"),
      const UnicodeEmoji("👩🏻‍🔬"),
      const UnicodeEmoji("👩🏼‍🔬"),
      const UnicodeEmoji("👩🏽‍🔬"),
      const UnicodeEmoji("👩🏾‍🔬"),
      const UnicodeEmoji("👩🏿‍🔬"),
      const UnicodeEmoji("👨‍🔬"),
      const UnicodeEmoji("👨🏻‍🔬"),
      const UnicodeEmoji("👨🏼‍🔬"),
      const UnicodeEmoji("👨🏽‍🔬"),
      const UnicodeEmoji("👨🏾‍🔬"),
      const UnicodeEmoji("👨🏿‍🔬"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍⚕️"), [
      const UnicodeEmoji("🧑‍⚕️"),
      const UnicodeEmoji("🧑🏻‍⚕️"),
      const UnicodeEmoji("🧑🏼‍⚕️"),
      const UnicodeEmoji("🧑🏽‍⚕️"),
      const UnicodeEmoji("🧑🏾‍⚕️"),
      const UnicodeEmoji("🧑🏿‍⚕️"),
      const UnicodeEmoji("👩‍⚕️"),
      const UnicodeEmoji("👩🏻‍⚕️"),
      const UnicodeEmoji("👩🏼‍⚕️"),
      const UnicodeEmoji("👩🏽‍⚕️"),
      const UnicodeEmoji("👩🏾‍⚕️"),
      const UnicodeEmoji("👩🏿‍⚕️"),
      const UnicodeEmoji("👨‍⚕️"),
      const UnicodeEmoji("👨🏻‍⚕️"),
      const UnicodeEmoji("👨🏼‍⚕️"),
      const UnicodeEmoji("👨🏽‍⚕️"),
      const UnicodeEmoji("👨🏾‍⚕️"),
      const UnicodeEmoji("👨🏿‍⚕️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🔧"), [
      const UnicodeEmoji("🧑‍🔧"),
      const UnicodeEmoji("🧑🏻‍🔧"),
      const UnicodeEmoji("🧑🏼‍🔧"),
      const UnicodeEmoji("🧑🏽‍🔧"),
      const UnicodeEmoji("🧑🏾‍🔧"),
      const UnicodeEmoji("🧑🏿‍🔧"),
      const UnicodeEmoji("👩‍🔧"),
      const UnicodeEmoji("👩🏻‍🔧"),
      const UnicodeEmoji("👩🏼‍🔧"),
      const UnicodeEmoji("👩🏽‍🔧"),
      const UnicodeEmoji("👩🏾‍🔧"),
      const UnicodeEmoji("👩🏿‍🔧"),
      const UnicodeEmoji("👨‍🔧"),
      const UnicodeEmoji("👨🏻‍🔧"),
      const UnicodeEmoji("👨🏼‍🔧"),
      const UnicodeEmoji("👨🏽‍🔧"),
      const UnicodeEmoji("👨🏾‍🔧"),
      const UnicodeEmoji("👨🏿‍🔧"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🏭"), [
      const UnicodeEmoji("🧑‍🏭"),
      const UnicodeEmoji("🧑🏻‍🏭"),
      const UnicodeEmoji("🧑🏼‍🏭"),
      const UnicodeEmoji("🧑🏽‍🏭"),
      const UnicodeEmoji("🧑🏾‍🏭"),
      const UnicodeEmoji("🧑🏿‍🏭"),
      const UnicodeEmoji("👩‍🏭"),
      const UnicodeEmoji("👩🏻‍🏭"),
      const UnicodeEmoji("👩🏼‍🏭"),
      const UnicodeEmoji("👩🏽‍🏭"),
      const UnicodeEmoji("👩🏾‍🏭"),
      const UnicodeEmoji("👩🏿‍🏭"),
      const UnicodeEmoji("👨‍🏭"),
      const UnicodeEmoji("👨🏻‍🏭"),
      const UnicodeEmoji("👨🏼‍🏭"),
      const UnicodeEmoji("👨🏽‍🏭"),
      const UnicodeEmoji("👨🏾‍🏭"),
      const UnicodeEmoji("👨🏿‍🏭"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🚒"), [
      const UnicodeEmoji("🧑‍🚒"),
      const UnicodeEmoji("🧑🏻‍🚒"),
      const UnicodeEmoji("🧑🏼‍🚒"),
      const UnicodeEmoji("🧑🏽‍🚒"),
      const UnicodeEmoji("🧑🏾‍🚒"),
      const UnicodeEmoji("🧑🏿‍🚒"),
      const UnicodeEmoji("👩‍🚒"),
      const UnicodeEmoji("👩🏻‍🚒"),
      const UnicodeEmoji("👩🏼‍🚒"),
      const UnicodeEmoji("👩🏽‍🚒"),
      const UnicodeEmoji("👩🏾‍🚒"),
      const UnicodeEmoji("👩🏿‍🚒"),
      const UnicodeEmoji("👨‍🚒"),
      const UnicodeEmoji("👨🏻‍🚒"),
      const UnicodeEmoji("👨🏼‍🚒"),
      const UnicodeEmoji("👨🏽‍🚒"),
      const UnicodeEmoji("👨🏾‍🚒"),
      const UnicodeEmoji("👨🏿‍🚒"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🌾"), [
      const UnicodeEmoji("🧑‍🌾"),
      const UnicodeEmoji("🧑🏻‍🌾"),
      const UnicodeEmoji("🧑🏼‍🌾"),
      const UnicodeEmoji("🧑🏽‍🌾"),
      const UnicodeEmoji("🧑🏾‍🌾"),
      const UnicodeEmoji("🧑🏿‍🌾"),
      const UnicodeEmoji("👩‍🌾"),
      const UnicodeEmoji("👩🏻‍🌾"),
      const UnicodeEmoji("👩🏼‍🌾"),
      const UnicodeEmoji("👩🏽‍🌾"),
      const UnicodeEmoji("👩🏾‍🌾"),
      const UnicodeEmoji("👩🏿‍🌾"),
      const UnicodeEmoji("👨‍🌾"),
      const UnicodeEmoji("👨🏻‍🌾"),
      const UnicodeEmoji("👨🏼‍🌾"),
      const UnicodeEmoji("👨🏽‍🌾"),
      const UnicodeEmoji("👨🏾‍🌾"),
      const UnicodeEmoji("👨🏿‍🌾"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🏫"), [
      const UnicodeEmoji("🧑‍🏫"),
      const UnicodeEmoji("🧑🏻‍🏫"),
      const UnicodeEmoji("🧑🏼‍🏫"),
      const UnicodeEmoji("🧑🏽‍🏫"),
      const UnicodeEmoji("🧑🏾‍🏫"),
      const UnicodeEmoji("🧑🏿‍🏫"),
      const UnicodeEmoji("👩‍🏫"),
      const UnicodeEmoji("👩🏻‍🏫"),
      const UnicodeEmoji("👩🏼‍🏫"),
      const UnicodeEmoji("👩🏽‍🏫"),
      const UnicodeEmoji("👩🏾‍🏫"),
      const UnicodeEmoji("👩🏿‍🏫"),
      const UnicodeEmoji("👨‍🏫"),
      const UnicodeEmoji("👨🏻‍🏫"),
      const UnicodeEmoji("👨🏼‍🏫"),
      const UnicodeEmoji("👨🏽‍🏫"),
      const UnicodeEmoji("👨🏾‍🏫"),
      const UnicodeEmoji("👨🏿‍🏫"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🎓"), [
      const UnicodeEmoji("🧑‍🎓"),
      const UnicodeEmoji("🧑🏻‍🎓"),
      const UnicodeEmoji("🧑🏼‍🎓"),
      const UnicodeEmoji("🧑🏽‍🎓"),
      const UnicodeEmoji("🧑🏾‍🎓"),
      const UnicodeEmoji("🧑🏿‍🎓"),
      const UnicodeEmoji("👩‍🎓"),
      const UnicodeEmoji("👩🏻‍🎓"),
      const UnicodeEmoji("👩🏼‍🎓"),
      const UnicodeEmoji("👩🏽‍🎓"),
      const UnicodeEmoji("👩🏾‍🎓"),
      const UnicodeEmoji("👩🏿‍🎓"),
      const UnicodeEmoji("👨‍🎓"),
      const UnicodeEmoji("👨🏻‍🎓"),
      const UnicodeEmoji("👨🏼‍🎓"),
      const UnicodeEmoji("👨🏽‍🎓"),
      const UnicodeEmoji("👨🏾‍🎓"),
      const UnicodeEmoji("👨🏿‍🎓"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍💼"), [
      const UnicodeEmoji("🧑‍💼"),
      const UnicodeEmoji("🧑🏻‍💼"),
      const UnicodeEmoji("🧑🏼‍💼"),
      const UnicodeEmoji("🧑🏽‍💼"),
      const UnicodeEmoji("🧑🏾‍💼"),
      const UnicodeEmoji("🧑🏿‍💼"),
      const UnicodeEmoji("👩‍💼"),
      const UnicodeEmoji("👩🏻‍💼"),
      const UnicodeEmoji("👩🏼‍💼"),
      const UnicodeEmoji("👩🏽‍💼"),
      const UnicodeEmoji("👩🏾‍💼"),
      const UnicodeEmoji("👩🏿‍💼"),
      const UnicodeEmoji("👨‍💼"),
      const UnicodeEmoji("👨🏻‍💼"),
      const UnicodeEmoji("👨🏼‍💼"),
      const UnicodeEmoji("👨🏽‍💼"),
      const UnicodeEmoji("👨🏾‍💼"),
      const UnicodeEmoji("👨🏿‍💼"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍⚖️"), [
      const UnicodeEmoji("🧑‍⚖️"),
      const UnicodeEmoji("🧑🏻‍⚖️"),
      const UnicodeEmoji("🧑🏼‍⚖️"),
      const UnicodeEmoji("🧑🏽‍⚖️"),
      const UnicodeEmoji("🧑🏾‍⚖️"),
      const UnicodeEmoji("🧑🏿‍⚖️"),
      const UnicodeEmoji("👩‍⚖️"),
      const UnicodeEmoji("👩🏻‍⚖️"),
      const UnicodeEmoji("👩🏼‍⚖️"),
      const UnicodeEmoji("👩🏽‍⚖️"),
      const UnicodeEmoji("👩🏾‍⚖️"),
      const UnicodeEmoji("👩🏿‍⚖️"),
      const UnicodeEmoji("👨‍⚖️"),
      const UnicodeEmoji("👨🏻‍⚖️"),
      const UnicodeEmoji("👨🏼‍⚖️"),
      const UnicodeEmoji("👨🏽‍⚖️"),
      const UnicodeEmoji("👨🏾‍⚖️"),
      const UnicodeEmoji("👨🏿‍⚖️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍💻"), [
      const UnicodeEmoji("🧑‍💻"),
      const UnicodeEmoji("🧑🏻‍💻"),
      const UnicodeEmoji("🧑🏼‍💻"),
      const UnicodeEmoji("🧑🏽‍💻"),
      const UnicodeEmoji("🧑🏾‍💻"),
      const UnicodeEmoji("🧑🏿‍💻"),
      const UnicodeEmoji("👩‍💻"),
      const UnicodeEmoji("👩🏻‍💻"),
      const UnicodeEmoji("👩🏼‍💻"),
      const UnicodeEmoji("👩🏽‍💻"),
      const UnicodeEmoji("👩🏾‍💻"),
      const UnicodeEmoji("👩🏿‍💻"),
      const UnicodeEmoji("👨‍💻"),
      const UnicodeEmoji("👨🏻‍💻"),
      const UnicodeEmoji("👨🏼‍💻"),
      const UnicodeEmoji("👨🏽‍💻"),
      const UnicodeEmoji("👨🏾‍💻"),
      const UnicodeEmoji("👨🏿‍💻"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🎤"), [
      const UnicodeEmoji("🧑‍🎤"),
      const UnicodeEmoji("🧑🏻‍🎤"),
      const UnicodeEmoji("🧑🏼‍🎤"),
      const UnicodeEmoji("🧑🏽‍🎤"),
      const UnicodeEmoji("🧑🏾‍🎤"),
      const UnicodeEmoji("🧑🏿‍🎤"),
      const UnicodeEmoji("👩‍🎤"),
      const UnicodeEmoji("👩🏻‍🎤"),
      const UnicodeEmoji("👩🏼‍🎤"),
      const UnicodeEmoji("👩🏽‍🎤"),
      const UnicodeEmoji("👩🏾‍🎤"),
      const UnicodeEmoji("👩🏿‍🎤"),
      const UnicodeEmoji("👨‍🎤"),
      const UnicodeEmoji("👨🏻‍🎤"),
      const UnicodeEmoji("👨🏼‍🎤"),
      const UnicodeEmoji("👨🏽‍🎤"),
      const UnicodeEmoji("👨🏾‍🎤"),
      const UnicodeEmoji("👨🏿‍🎤"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🎨"), [
      const UnicodeEmoji("🧑‍🎨"),
      const UnicodeEmoji("🧑🏻‍🎨"),
      const UnicodeEmoji("🧑🏼‍🎨"),
      const UnicodeEmoji("🧑🏽‍🎨"),
      const UnicodeEmoji("🧑🏾‍🎨"),
      const UnicodeEmoji("🧑🏿‍🎨"),
      const UnicodeEmoji("👩‍🎨"),
      const UnicodeEmoji("👩🏻‍🎨"),
      const UnicodeEmoji("👩🏼‍🎨"),
      const UnicodeEmoji("👩🏽‍🎨"),
      const UnicodeEmoji("👩🏾‍🎨"),
      const UnicodeEmoji("👩🏿‍🎨"),
      const UnicodeEmoji("👨‍🎨"),
      const UnicodeEmoji("👨🏻‍🎨"),
      const UnicodeEmoji("👨🏼‍🎨"),
      const UnicodeEmoji("👨🏽‍🎨"),
      const UnicodeEmoji("👨🏾‍🎨"),
      const UnicodeEmoji("👨🏿‍🎨"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🍳"), [
      const UnicodeEmoji("🧑‍🍳"),
      const UnicodeEmoji("🧑🏻‍🍳"),
      const UnicodeEmoji("🧑🏼‍🍳"),
      const UnicodeEmoji("🧑🏽‍🍳"),
      const UnicodeEmoji("🧑🏾‍🍳"),
      const UnicodeEmoji("🧑🏿‍🍳"),
      const UnicodeEmoji("👩‍🍳"),
      const UnicodeEmoji("👩🏻‍🍳"),
      const UnicodeEmoji("👩🏼‍🍳"),
      const UnicodeEmoji("👩🏽‍🍳"),
      const UnicodeEmoji("👩🏾‍🍳"),
      const UnicodeEmoji("👩🏿‍🍳"),
      const UnicodeEmoji("👨‍🍳"),
      const UnicodeEmoji("👨🏻‍🍳"),
      const UnicodeEmoji("👨🏼‍🍳"),
      const UnicodeEmoji("👨🏽‍🍳"),
      const UnicodeEmoji("👨🏾‍🍳"),
      const UnicodeEmoji("👨🏿‍🍳"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👳"), [
      const UnicodeEmoji("👳"),
      const UnicodeEmoji("👳🏻"),
      const UnicodeEmoji("👳🏼"),
      const UnicodeEmoji("👳🏽"),
      const UnicodeEmoji("👳🏾"),
      const UnicodeEmoji("👳🏿"),
      const UnicodeEmoji("👳‍♀️"),
      const UnicodeEmoji("👳🏻‍♀️"),
      const UnicodeEmoji("👳🏼‍♀️"),
      const UnicodeEmoji("👳🏽‍♀️"),
      const UnicodeEmoji("👳🏾‍♀️"),
      const UnicodeEmoji("👳🏿‍♀️"),
      const UnicodeEmoji("👳‍♂️"),
      const UnicodeEmoji("👳🏻‍♂️"),
      const UnicodeEmoji("👳🏼‍♂️"),
      const UnicodeEmoji("👳🏽‍♂️"),
      const UnicodeEmoji("👳🏾‍♂️"),
      const UnicodeEmoji("👳🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧕"), [
      const UnicodeEmoji("🧕"),
      const UnicodeEmoji("🧕🏻"),
      const UnicodeEmoji("🧕🏼"),
      const UnicodeEmoji("🧕🏽"),
      const UnicodeEmoji("🧕🏾"),
      const UnicodeEmoji("🧕🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👲"), [
      const UnicodeEmoji("👲"),
      const UnicodeEmoji("👲🏻"),
      const UnicodeEmoji("👲🏼"),
      const UnicodeEmoji("👲🏽"),
      const UnicodeEmoji("👲🏾"),
      const UnicodeEmoji("👲🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👶"), [
      const UnicodeEmoji("👶"),
      const UnicodeEmoji("👶🏻"),
      const UnicodeEmoji("👶🏼"),
      const UnicodeEmoji("👶🏽"),
      const UnicodeEmoji("👶🏾"),
      const UnicodeEmoji("👶🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧒"), [
      const UnicodeEmoji("🧒"),
      const UnicodeEmoji("🧒🏻"),
      const UnicodeEmoji("🧒🏼"),
      const UnicodeEmoji("🧒🏽"),
      const UnicodeEmoji("🧒🏾"),
      const UnicodeEmoji("🧒🏿"),
      const UnicodeEmoji("👧"),
      const UnicodeEmoji("👧🏻"),
      const UnicodeEmoji("👧🏼"),
      const UnicodeEmoji("👧🏽"),
      const UnicodeEmoji("👧🏾"),
      const UnicodeEmoji("👧🏿"),
      const UnicodeEmoji("👦"),
      const UnicodeEmoji("👦🏻"),
      const UnicodeEmoji("👦🏼"),
      const UnicodeEmoji("👦🏽"),
      const UnicodeEmoji("👦🏾"),
      const UnicodeEmoji("👦🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑"), [
      const UnicodeEmoji("🧑"),
      const UnicodeEmoji("🧑🏻"),
      const UnicodeEmoji("🧑🏼"),
      const UnicodeEmoji("🧑🏽"),
      const UnicodeEmoji("🧑🏾"),
      const UnicodeEmoji("🧑🏿"),
      const UnicodeEmoji("👩"),
      const UnicodeEmoji("👩🏻"),
      const UnicodeEmoji("👩🏼"),
      const UnicodeEmoji("👩🏽"),
      const UnicodeEmoji("👩🏾"),
      const UnicodeEmoji("👩🏿"),
      const UnicodeEmoji("👨"),
      const UnicodeEmoji("👨🏻"),
      const UnicodeEmoji("👨🏼"),
      const UnicodeEmoji("👨🏽"),
      const UnicodeEmoji("👨🏾"),
      const UnicodeEmoji("👨🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧓"), [
      const UnicodeEmoji("🧓"),
      const UnicodeEmoji("🧓🏻"),
      const UnicodeEmoji("🧓🏼"),
      const UnicodeEmoji("🧓🏽"),
      const UnicodeEmoji("🧓🏾"),
      const UnicodeEmoji("🧓🏿"),
      const UnicodeEmoji("👵"),
      const UnicodeEmoji("👵🏻"),
      const UnicodeEmoji("👵🏼"),
      const UnicodeEmoji("👵🏽"),
      const UnicodeEmoji("👵🏾"),
      const UnicodeEmoji("👵🏿"),
      const UnicodeEmoji("👴"),
      const UnicodeEmoji("👴🏻"),
      const UnicodeEmoji("👴🏼"),
      const UnicodeEmoji("👴🏽"),
      const UnicodeEmoji("👴🏾"),
      const UnicodeEmoji("👴🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🦳"), [
      const UnicodeEmoji("🧑‍🦳"),
      const UnicodeEmoji("🧑🏻‍🦳"),
      const UnicodeEmoji("🧑🏼‍🦳"),
      const UnicodeEmoji("🧑🏽‍🦳"),
      const UnicodeEmoji("🧑🏾‍🦳"),
      const UnicodeEmoji("🧑🏿‍🦳"),
      const UnicodeEmoji("👩‍🦳"),
      const UnicodeEmoji("👩🏻‍🦳"),
      const UnicodeEmoji("👩🏼‍🦳"),
      const UnicodeEmoji("👩🏽‍🦳"),
      const UnicodeEmoji("👩🏾‍🦳"),
      const UnicodeEmoji("👩🏿‍🦳"),
      const UnicodeEmoji("👨‍🦳"),
      const UnicodeEmoji("👨🏻‍🦳"),
      const UnicodeEmoji("👨🏼‍🦳"),
      const UnicodeEmoji("👨🏽‍🦳"),
      const UnicodeEmoji("👨🏾‍🦳"),
      const UnicodeEmoji("👨🏿‍🦳"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🦰"), [
      const UnicodeEmoji("🧑‍🦰"),
      const UnicodeEmoji("🧑🏻‍🦰"),
      const UnicodeEmoji("🧑🏼‍🦰"),
      const UnicodeEmoji("🧑🏽‍🦰"),
      const UnicodeEmoji("🧑🏾‍🦰"),
      const UnicodeEmoji("🧑🏿‍🦰"),
      const UnicodeEmoji("👩‍🦰"),
      const UnicodeEmoji("👩🏻‍🦰"),
      const UnicodeEmoji("👩🏼‍🦰"),
      const UnicodeEmoji("👩🏽‍🦰"),
      const UnicodeEmoji("👩🏾‍🦰"),
      const UnicodeEmoji("👩🏿‍🦰"),
      const UnicodeEmoji("👨‍🦰"),
      const UnicodeEmoji("👨🏻‍🦰"),
      const UnicodeEmoji("👨🏼‍🦰"),
      const UnicodeEmoji("👨🏽‍🦰"),
      const UnicodeEmoji("👨🏾‍🦰"),
      const UnicodeEmoji("👨🏿‍🦰"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👱"), [
      const UnicodeEmoji("👱"),
      const UnicodeEmoji("👱🏻"),
      const UnicodeEmoji("👱🏼"),
      const UnicodeEmoji("👱🏽"),
      const UnicodeEmoji("👱🏾"),
      const UnicodeEmoji("👱🏿"),
      const UnicodeEmoji("👱‍♀️"),
      const UnicodeEmoji("👱🏻‍♀️"),
      const UnicodeEmoji("👱🏼‍♀️"),
      const UnicodeEmoji("👱🏽‍♀️"),
      const UnicodeEmoji("👱🏾‍♀️"),
      const UnicodeEmoji("👱🏿‍♀️"),
      const UnicodeEmoji("👱‍♂️"),
      const UnicodeEmoji("👱🏻‍♂️"),
      const UnicodeEmoji("👱🏼‍♂️"),
      const UnicodeEmoji("👱🏽‍♂️"),
      const UnicodeEmoji("👱🏾‍♂️"),
      const UnicodeEmoji("👱🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🦱"), [
      const UnicodeEmoji("🧑‍🦱"),
      const UnicodeEmoji("🧑🏻‍🦱"),
      const UnicodeEmoji("🧑🏼‍🦱"),
      const UnicodeEmoji("🧑🏽‍🦱"),
      const UnicodeEmoji("🧑🏾‍🦱"),
      const UnicodeEmoji("🧑🏿‍🦱"),
      const UnicodeEmoji("👩‍🦱"),
      const UnicodeEmoji("👩🏻‍🦱"),
      const UnicodeEmoji("👩🏼‍🦱"),
      const UnicodeEmoji("👩🏽‍🦱"),
      const UnicodeEmoji("👩🏾‍🦱"),
      const UnicodeEmoji("👩🏿‍🦱"),
      const UnicodeEmoji("👨‍🦱"),
      const UnicodeEmoji("👨🏻‍🦱"),
      const UnicodeEmoji("👨🏼‍🦱"),
      const UnicodeEmoji("👨🏽‍🦱"),
      const UnicodeEmoji("👨🏾‍🦱"),
      const UnicodeEmoji("👨🏿‍🦱"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🦲"), [
      const UnicodeEmoji("🧑‍🦲"),
      const UnicodeEmoji("🧑🏻‍🦲"),
      const UnicodeEmoji("🧑🏼‍🦲"),
      const UnicodeEmoji("🧑🏽‍🦲"),
      const UnicodeEmoji("🧑🏾‍🦲"),
      const UnicodeEmoji("🧑🏿‍🦲"),
      const UnicodeEmoji("👩‍🦲"),
      const UnicodeEmoji("👩🏻‍🦲"),
      const UnicodeEmoji("👩🏼‍🦲"),
      const UnicodeEmoji("👩🏽‍🦲"),
      const UnicodeEmoji("👩🏾‍🦲"),
      const UnicodeEmoji("👩🏿‍🦲"),
      const UnicodeEmoji("👨‍🦲"),
      const UnicodeEmoji("👨🏻‍🦲"),
      const UnicodeEmoji("👨🏼‍🦲"),
      const UnicodeEmoji("👨🏽‍🦲"),
      const UnicodeEmoji("👨🏾‍🦲"),
      const UnicodeEmoji("👨🏿‍🦲"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧔"), [
      const UnicodeEmoji("🧔"),
      const UnicodeEmoji("🧔🏻"),
      const UnicodeEmoji("🧔🏼"),
      const UnicodeEmoji("🧔🏽"),
      const UnicodeEmoji("🧔🏾"),
      const UnicodeEmoji("🧔🏿"),
      const UnicodeEmoji("🧔‍♀️"),
      const UnicodeEmoji("🧔🏻‍♀️"),
      const UnicodeEmoji("🧔🏼‍♀️"),
      const UnicodeEmoji("🧔🏽‍♀️"),
      const UnicodeEmoji("🧔🏾‍♀️"),
      const UnicodeEmoji("🧔🏿‍♀️"),
      const UnicodeEmoji("🧔‍♂️"),
      const UnicodeEmoji("🧔🏻‍♂️"),
      const UnicodeEmoji("🧔🏼‍♂️"),
      const UnicodeEmoji("🧔🏽‍♂️"),
      const UnicodeEmoji("🧔🏾‍♂️"),
      const UnicodeEmoji("🧔🏿‍♂️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🕴️"), [
      const UnicodeEmoji("🕴️"),
      const UnicodeEmoji("🕴🏻"),
      const UnicodeEmoji("🕴🏼"),
      const UnicodeEmoji("🕴🏽"),
      const UnicodeEmoji("🕴🏾"),
      const UnicodeEmoji("🕴🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("💃"), [
      const UnicodeEmoji("💃"),
      const UnicodeEmoji("💃🏻"),
      const UnicodeEmoji("💃🏼"),
      const UnicodeEmoji("💃🏽"),
      const UnicodeEmoji("💃🏾"),
      const UnicodeEmoji("💃🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🕺"), [
      const UnicodeEmoji("🕺"),
      const UnicodeEmoji("🕺🏻"),
      const UnicodeEmoji("🕺🏼"),
      const UnicodeEmoji("🕺🏽"),
      const UnicodeEmoji("🕺🏾"),
      const UnicodeEmoji("🕺🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👯"), [
      const UnicodeEmoji("👯"),
      const UnicodeEmoji("👯‍♂️"),
      const UnicodeEmoji("👯‍♀️"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🤝‍🧑"), [
      const UnicodeEmoji("🧑‍🤝‍🧑"),
      const UnicodeEmoji("🧑🏻‍🤝‍🧑🏻"),
      const UnicodeEmoji("🧑🏻‍🤝‍🧑🏼"),
      const UnicodeEmoji("🧑🏻‍🤝‍🧑🏽"),
      const UnicodeEmoji("🧑🏻‍🤝‍🧑🏾"),
      const UnicodeEmoji("🧑🏻‍🤝‍🧑🏿"),
      const UnicodeEmoji("🧑🏼‍🤝‍🧑🏻"),
      const UnicodeEmoji("🧑🏼‍🤝‍🧑🏼"),
      const UnicodeEmoji("🧑🏼‍🤝‍🧑🏽"),
      const UnicodeEmoji("🧑🏼‍🤝‍🧑🏾"),
      const UnicodeEmoji("🧑🏼‍🤝‍🧑🏿"),
      const UnicodeEmoji("🧑🏽‍🤝‍🧑🏻"),
      const UnicodeEmoji("🧑🏽‍🤝‍🧑🏼"),
      const UnicodeEmoji("🧑🏽‍🤝‍🧑🏽"),
      const UnicodeEmoji("🧑🏽‍🤝‍🧑🏾"),
      const UnicodeEmoji("🧑🏽‍🤝‍🧑🏿"),
      const UnicodeEmoji("🧑🏾‍🤝‍🧑🏻"),
      const UnicodeEmoji("🧑🏾‍🤝‍🧑🏼"),
      const UnicodeEmoji("🧑🏾‍🤝‍🧑🏽"),
      const UnicodeEmoji("🧑🏾‍🤝‍🧑🏾"),
      const UnicodeEmoji("🧑🏾‍🤝‍🧑🏿"),
      const UnicodeEmoji("🧑🏿‍🤝‍🧑🏻"),
      const UnicodeEmoji("🧑🏿‍🤝‍🧑🏼"),
      const UnicodeEmoji("🧑🏿‍🤝‍🧑🏽"),
      const UnicodeEmoji("🧑🏿‍🤝‍🧑🏾"),
      const UnicodeEmoji("🧑🏿‍🤝‍🧑🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👭"), [
      const UnicodeEmoji("👭"),
      const UnicodeEmoji("👭🏻"),
      const UnicodeEmoji("👩🏻‍🤝‍👩🏼"),
      const UnicodeEmoji("👩🏻‍🤝‍👩🏽"),
      const UnicodeEmoji("👩🏻‍🤝‍👩🏾"),
      const UnicodeEmoji("👩🏻‍🤝‍👩🏿"),
      const UnicodeEmoji("👩🏼‍🤝‍👩🏻"),
      const UnicodeEmoji("👭🏼"),
      const UnicodeEmoji("👩🏼‍🤝‍👩🏽"),
      const UnicodeEmoji("👩🏼‍🤝‍👩🏾"),
      const UnicodeEmoji("👩🏼‍🤝‍👩🏿"),
      const UnicodeEmoji("👩🏽‍🤝‍👩🏻"),
      const UnicodeEmoji("👩🏽‍🤝‍👩🏼"),
      const UnicodeEmoji("👭🏽"),
      const UnicodeEmoji("👩🏽‍🤝‍👩🏾"),
      const UnicodeEmoji("👩🏽‍🤝‍👩🏿"),
      const UnicodeEmoji("👩🏾‍🤝‍👩🏻"),
      const UnicodeEmoji("👩🏾‍🤝‍👩🏼"),
      const UnicodeEmoji("👩🏾‍🤝‍👩🏽"),
      const UnicodeEmoji("👭🏾"),
      const UnicodeEmoji("👩🏾‍🤝‍👩🏿"),
      const UnicodeEmoji("👩🏿‍🤝‍👩🏻"),
      const UnicodeEmoji("👩🏿‍🤝‍👩🏼"),
      const UnicodeEmoji("👩🏿‍🤝‍👩🏽"),
      const UnicodeEmoji("👩🏿‍🤝‍👩🏾"),
      const UnicodeEmoji("👭🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👬"), [
      const UnicodeEmoji("👬"),
      const UnicodeEmoji("👬🏻"),
      const UnicodeEmoji("👨🏻‍🤝‍👨🏼"),
      const UnicodeEmoji("👨🏻‍🤝‍👨🏽"),
      const UnicodeEmoji("👨🏻‍🤝‍👨🏾"),
      const UnicodeEmoji("👨🏻‍🤝‍👨🏿"),
      const UnicodeEmoji("👨🏼‍🤝‍👨🏻"),
      const UnicodeEmoji("👬🏼"),
      const UnicodeEmoji("👨🏼‍🤝‍👨🏽"),
      const UnicodeEmoji("👨🏼‍🤝‍👨🏾"),
      const UnicodeEmoji("👨🏼‍🤝‍👨🏿"),
      const UnicodeEmoji("👨🏽‍🤝‍👨🏻"),
      const UnicodeEmoji("👨🏽‍🤝‍👨🏼"),
      const UnicodeEmoji("👬🏽"),
      const UnicodeEmoji("👨🏽‍🤝‍👨🏾"),
      const UnicodeEmoji("👨🏽‍🤝‍👨🏿"),
      const UnicodeEmoji("👨🏾‍🤝‍👨🏻"),
      const UnicodeEmoji("👨🏾‍🤝‍👨🏼"),
      const UnicodeEmoji("👨🏾‍🤝‍👨🏽"),
      const UnicodeEmoji("👬🏾"),
      const UnicodeEmoji("👨🏾‍🤝‍👨🏿"),
      const UnicodeEmoji("👨🏿‍🤝‍👨🏻"),
      const UnicodeEmoji("👨🏿‍🤝‍👨🏼"),
      const UnicodeEmoji("👨🏿‍🤝‍👨🏽"),
      const UnicodeEmoji("👨🏿‍🤝‍👨🏾"),
      const UnicodeEmoji("👬🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👫"), [
      const UnicodeEmoji("👫"),
      const UnicodeEmoji("👫🏻"),
      const UnicodeEmoji("👩🏻‍🤝‍👨🏼"),
      const UnicodeEmoji("👩🏻‍🤝‍👨🏽"),
      const UnicodeEmoji("👩🏻‍🤝‍👨🏾"),
      const UnicodeEmoji("👩🏻‍🤝‍👨🏿"),
      const UnicodeEmoji("👩🏼‍🤝‍👨🏻"),
      const UnicodeEmoji("👫🏼"),
      const UnicodeEmoji("👩🏼‍🤝‍👨🏽"),
      const UnicodeEmoji("👩🏼‍🤝‍👨🏾"),
      const UnicodeEmoji("👩🏼‍🤝‍👨🏿"),
      const UnicodeEmoji("👩🏽‍🤝‍👨🏻"),
      const UnicodeEmoji("👩🏽‍🤝‍👨🏼"),
      const UnicodeEmoji("👫🏽"),
      const UnicodeEmoji("👩🏽‍🤝‍👨🏾"),
      const UnicodeEmoji("👩🏽‍🤝‍👨🏿"),
      const UnicodeEmoji("👩🏾‍🤝‍👨🏻"),
      const UnicodeEmoji("👩🏾‍🤝‍👨🏼"),
      const UnicodeEmoji("👩🏾‍🤝‍👨🏽"),
      const UnicodeEmoji("👫🏾"),
      const UnicodeEmoji("👩🏾‍🤝‍👨🏿"),
      const UnicodeEmoji("👩🏿‍🤝‍👨🏻"),
      const UnicodeEmoji("👩🏿‍🤝‍👨🏼"),
      const UnicodeEmoji("👩🏿‍🤝‍👨🏽"),
      const UnicodeEmoji("👩🏿‍🤝‍👨🏾"),
      const UnicodeEmoji("👫🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("💏"), [
      const UnicodeEmoji("💏"),
      const UnicodeEmoji("💏🏻"),
      const UnicodeEmoji("🧑🏻‍❤️‍💋‍🧑🏼"),
      const UnicodeEmoji("🧑🏻‍❤️‍💋‍🧑🏽"),
      const UnicodeEmoji("🧑🏻‍❤️‍💋‍🧑🏾"),
      const UnicodeEmoji("🧑🏻‍❤️‍💋‍🧑🏿"),
      const UnicodeEmoji("🧑🏼‍❤️‍💋‍🧑🏻"),
      const UnicodeEmoji("💏🏼"),
      const UnicodeEmoji("🧑🏼‍❤️‍💋‍🧑🏽"),
      const UnicodeEmoji("🧑🏼‍❤️‍💋‍🧑🏾"),
      const UnicodeEmoji("🧑🏼‍❤️‍💋‍🧑🏿"),
      const UnicodeEmoji("🧑🏽‍❤️‍💋‍🧑🏻"),
      const UnicodeEmoji("🧑🏽‍❤️‍💋‍🧑🏼"),
      const UnicodeEmoji("💏🏽"),
      const UnicodeEmoji("🧑🏽‍❤️‍💋‍🧑🏾"),
      const UnicodeEmoji("🧑🏽‍❤️‍💋‍🧑🏿"),
      const UnicodeEmoji("🧑🏾‍❤️‍💋‍🧑🏻"),
      const UnicodeEmoji("🧑🏾‍❤️‍💋‍🧑🏼"),
      const UnicodeEmoji("🧑🏾‍❤️‍💋‍🧑🏽"),
      const UnicodeEmoji("💏🏾"),
      const UnicodeEmoji("🧑🏾‍❤️‍💋‍🧑🏿"),
      const UnicodeEmoji("🧑🏿‍❤️‍💋‍🧑🏻"),
      const UnicodeEmoji("🧑🏿‍❤️‍💋‍🧑🏼"),
      const UnicodeEmoji("🧑🏿‍❤️‍💋‍🧑🏽"),
      const UnicodeEmoji("🧑🏿‍❤️‍💋‍🧑🏾"),
      const UnicodeEmoji("💏🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👩‍❤️‍💋‍👨"), [
      const UnicodeEmoji("👩‍❤️‍💋‍👨"),
      const UnicodeEmoji("👩🏻‍❤️‍💋‍👨🏻"),
      const UnicodeEmoji("👩🏻‍❤️‍💋‍👨🏼"),
      const UnicodeEmoji("👩🏻‍❤️‍💋‍👨🏽"),
      const UnicodeEmoji("👩🏻‍❤️‍💋‍👨🏾"),
      const UnicodeEmoji("👩🏻‍❤️‍💋‍👨🏿"),
      const UnicodeEmoji("👩🏼‍❤️‍💋‍👨🏻"),
      const UnicodeEmoji("👩🏼‍❤️‍💋‍👨🏼"),
      const UnicodeEmoji("👩🏼‍❤️‍💋‍👨🏽"),
      const UnicodeEmoji("👩🏼‍❤️‍💋‍👨🏾"),
      const UnicodeEmoji("👩🏼‍❤️‍💋‍👨🏿"),
      const UnicodeEmoji("👩🏽‍❤️‍💋‍👨🏻"),
      const UnicodeEmoji("👩🏽‍❤️‍💋‍👨🏼"),
      const UnicodeEmoji("👩🏽‍❤️‍💋‍👨🏽"),
      const UnicodeEmoji("👩🏽‍❤️‍💋‍👨🏾"),
      const UnicodeEmoji("👩🏽‍❤️‍💋‍👨🏿"),
      const UnicodeEmoji("👩🏾‍❤️‍💋‍👨🏻"),
      const UnicodeEmoji("👩🏾‍❤️‍💋‍👨🏼"),
      const UnicodeEmoji("👩🏾‍❤️‍💋‍👨🏽"),
      const UnicodeEmoji("👩🏾‍❤️‍💋‍👨🏾"),
      const UnicodeEmoji("👩🏾‍❤️‍💋‍👨🏿"),
      const UnicodeEmoji("👩🏿‍❤️‍💋‍👨🏻"),
      const UnicodeEmoji("👩🏿‍❤️‍💋‍👨🏼"),
      const UnicodeEmoji("👩🏿‍❤️‍💋‍👨🏽"),
      const UnicodeEmoji("👩🏿‍❤️‍💋‍👨🏾"),
      const UnicodeEmoji("👩🏿‍❤️‍💋‍👨🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👨‍❤️‍💋‍👨"), [
      const UnicodeEmoji("👨‍❤️‍💋‍👨"),
      const UnicodeEmoji("👨🏻‍❤️‍💋‍👨🏻"),
      const UnicodeEmoji("👨🏻‍❤️‍💋‍👨🏼"),
      const UnicodeEmoji("👨🏻‍❤️‍💋‍👨🏽"),
      const UnicodeEmoji("👨🏻‍❤️‍💋‍👨🏾"),
      const UnicodeEmoji("👨🏻‍❤️‍💋‍👨🏿"),
      const UnicodeEmoji("👨🏼‍❤️‍💋‍👨🏻"),
      const UnicodeEmoji("👨🏼‍❤️‍💋‍👨🏼"),
      const UnicodeEmoji("👨🏼‍❤️‍💋‍👨🏽"),
      const UnicodeEmoji("👨🏼‍❤️‍💋‍👨🏾"),
      const UnicodeEmoji("👨🏼‍❤️‍💋‍👨🏿"),
      const UnicodeEmoji("👨🏽‍❤️‍💋‍👨🏻"),
      const UnicodeEmoji("👨🏽‍❤️‍💋‍👨🏼"),
      const UnicodeEmoji("👨🏽‍❤️‍💋‍👨🏽"),
      const UnicodeEmoji("👨🏽‍❤️‍💋‍👨🏾"),
      const UnicodeEmoji("👨🏽‍❤️‍💋‍👨🏿"),
      const UnicodeEmoji("👨🏾‍❤️‍💋‍👨🏻"),
      const UnicodeEmoji("👨🏾‍❤️‍💋‍👨🏼"),
      const UnicodeEmoji("👨🏾‍❤️‍💋‍👨🏽"),
      const UnicodeEmoji("👨🏾‍❤️‍💋‍👨🏾"),
      const UnicodeEmoji("👨🏾‍❤️‍💋‍👨🏿"),
      const UnicodeEmoji("👨🏿‍❤️‍💋‍👨🏻"),
      const UnicodeEmoji("👨🏿‍❤️‍💋‍👨🏼"),
      const UnicodeEmoji("👨🏿‍❤️‍💋‍👨🏽"),
      const UnicodeEmoji("👨🏿‍❤️‍💋‍👨🏾"),
      const UnicodeEmoji("👨🏿‍❤️‍💋‍👨🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👩‍❤️‍💋‍👩"), [
      const UnicodeEmoji("👩‍❤️‍💋‍👩"),
      const UnicodeEmoji("👩🏻‍❤️‍💋‍👩🏻"),
      const UnicodeEmoji("👩🏻‍❤️‍💋‍👩🏼"),
      const UnicodeEmoji("👩🏻‍❤️‍💋‍👩🏽"),
      const UnicodeEmoji("👩🏻‍❤️‍💋‍👩🏾"),
      const UnicodeEmoji("👩🏻‍❤️‍💋‍👩🏿"),
      const UnicodeEmoji("👩🏼‍❤️‍💋‍👩🏻"),
      const UnicodeEmoji("👩🏼‍❤️‍💋‍👩🏼"),
      const UnicodeEmoji("👩🏼‍❤️‍💋‍👩🏽"),
      const UnicodeEmoji("👩🏼‍❤️‍💋‍👩🏾"),
      const UnicodeEmoji("👩🏼‍❤️‍💋‍👩🏿"),
      const UnicodeEmoji("👩🏽‍❤️‍💋‍👩🏻"),
      const UnicodeEmoji("👩🏽‍❤️‍💋‍👩🏼"),
      const UnicodeEmoji("👩🏽‍❤️‍💋‍👩🏽"),
      const UnicodeEmoji("👩🏽‍❤️‍💋‍👩🏾"),
      const UnicodeEmoji("👩🏽‍❤️‍💋‍👩🏿"),
      const UnicodeEmoji("👩🏾‍❤️‍💋‍👩🏻"),
      const UnicodeEmoji("👩🏾‍❤️‍💋‍👩🏼"),
      const UnicodeEmoji("👩🏾‍❤️‍💋‍👩🏽"),
      const UnicodeEmoji("👩🏾‍❤️‍💋‍👩🏾"),
      const UnicodeEmoji("👩🏾‍❤️‍💋‍👩🏿"),
      const UnicodeEmoji("👩🏿‍❤️‍💋‍👩🏻"),
      const UnicodeEmoji("👩🏿‍❤️‍💋‍👩🏼"),
      const UnicodeEmoji("👩🏿‍❤️‍💋‍👩🏽"),
      const UnicodeEmoji("👩🏿‍❤️‍💋‍👩🏾"),
      const UnicodeEmoji("👩🏿‍❤️‍💋‍👩🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("💑"), [
      const UnicodeEmoji("💑"),
      const UnicodeEmoji("💑🏻"),
      const UnicodeEmoji("🧑🏻‍❤️‍🧑🏼"),
      const UnicodeEmoji("🧑🏻‍❤️‍🧑🏽"),
      const UnicodeEmoji("🧑🏻‍❤️‍🧑🏾"),
      const UnicodeEmoji("🧑🏻‍❤️‍🧑🏿"),
      const UnicodeEmoji("🧑🏼‍❤️‍🧑🏻"),
      const UnicodeEmoji("💑🏼"),
      const UnicodeEmoji("🧑🏼‍❤️‍🧑🏽"),
      const UnicodeEmoji("🧑🏼‍❤️‍🧑🏾"),
      const UnicodeEmoji("🧑🏼‍❤️‍🧑🏿"),
      const UnicodeEmoji("🧑🏽‍❤️‍🧑🏻"),
      const UnicodeEmoji("🧑🏽‍❤️‍🧑🏼"),
      const UnicodeEmoji("💑🏽"),
      const UnicodeEmoji("🧑🏽‍❤️‍🧑🏾"),
      const UnicodeEmoji("🧑🏽‍❤️‍🧑🏿"),
      const UnicodeEmoji("🧑🏾‍❤️‍🧑🏻"),
      const UnicodeEmoji("🧑🏾‍❤️‍🧑🏼"),
      const UnicodeEmoji("🧑🏾‍❤️‍🧑🏽"),
      const UnicodeEmoji("💑🏾"),
      const UnicodeEmoji("🧑🏾‍❤️‍🧑🏿"),
      const UnicodeEmoji("🧑🏿‍❤️‍🧑🏻"),
      const UnicodeEmoji("🧑🏿‍❤️‍🧑🏼"),
      const UnicodeEmoji("🧑🏿‍❤️‍🧑🏽"),
      const UnicodeEmoji("🧑🏿‍❤️‍🧑🏾"),
      const UnicodeEmoji("💑🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👩‍❤️‍👨"), [
      const UnicodeEmoji("👩‍❤️‍👨"),
      const UnicodeEmoji("👩🏻‍❤️‍👨🏻"),
      const UnicodeEmoji("👩🏻‍❤️‍👨🏼"),
      const UnicodeEmoji("👩🏻‍❤️‍👨🏽"),
      const UnicodeEmoji("👩🏻‍❤️‍👨🏾"),
      const UnicodeEmoji("👩🏻‍❤️‍👨🏿"),
      const UnicodeEmoji("👩🏼‍❤️‍👨🏻"),
      const UnicodeEmoji("👩🏼‍❤️‍👨🏼"),
      const UnicodeEmoji("👩🏼‍❤️‍👨🏽"),
      const UnicodeEmoji("👩🏼‍❤️‍👨🏾"),
      const UnicodeEmoji("👩🏼‍❤️‍👨🏿"),
      const UnicodeEmoji("👩🏽‍❤️‍👨🏻"),
      const UnicodeEmoji("👩🏽‍❤️‍👨🏼"),
      const UnicodeEmoji("👩🏽‍❤️‍👨🏽"),
      const UnicodeEmoji("👩🏽‍❤️‍👨🏾"),
      const UnicodeEmoji("👩🏽‍❤️‍👨🏿"),
      const UnicodeEmoji("👩🏾‍❤️‍👨🏻"),
      const UnicodeEmoji("👩🏾‍❤️‍👨🏼"),
      const UnicodeEmoji("👩🏾‍❤️‍👨🏽"),
      const UnicodeEmoji("👩🏾‍❤️‍👨🏾"),
      const UnicodeEmoji("👩🏾‍❤️‍👨🏿"),
      const UnicodeEmoji("👩🏿‍❤️‍👨🏻"),
      const UnicodeEmoji("👩🏿‍❤️‍👨🏼"),
      const UnicodeEmoji("👩🏿‍❤️‍👨🏽"),
      const UnicodeEmoji("👩🏿‍❤️‍👨🏾"),
      const UnicodeEmoji("👩🏿‍❤️‍👨🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👨‍❤️‍👨"), [
      const UnicodeEmoji("👨‍❤️‍👨"),
      const UnicodeEmoji("👨🏻‍❤️‍👨🏻"),
      const UnicodeEmoji("👨🏻‍❤️‍👨🏼"),
      const UnicodeEmoji("👨🏻‍❤️‍👨🏽"),
      const UnicodeEmoji("👨🏻‍❤️‍👨🏾"),
      const UnicodeEmoji("👨🏻‍❤️‍👨🏿"),
      const UnicodeEmoji("👨🏼‍❤️‍👨🏻"),
      const UnicodeEmoji("👨🏼‍❤️‍👨🏼"),
      const UnicodeEmoji("👨🏼‍❤️‍👨🏽"),
      const UnicodeEmoji("👨🏼‍❤️‍👨🏾"),
      const UnicodeEmoji("👨🏼‍❤️‍👨🏿"),
      const UnicodeEmoji("👨🏽‍❤️‍👨🏻"),
      const UnicodeEmoji("👨🏽‍❤️‍👨🏼"),
      const UnicodeEmoji("👨🏽‍❤️‍👨🏽"),
      const UnicodeEmoji("👨🏽‍❤️‍👨🏾"),
      const UnicodeEmoji("👨🏽‍❤️‍👨🏿"),
      const UnicodeEmoji("👨🏾‍❤️‍👨🏻"),
      const UnicodeEmoji("👨🏾‍❤️‍👨🏼"),
      const UnicodeEmoji("👨🏾‍❤️‍👨🏽"),
      const UnicodeEmoji("👨🏾‍❤️‍👨🏾"),
      const UnicodeEmoji("👨🏾‍❤️‍👨🏿"),
      const UnicodeEmoji("👨🏿‍❤️‍👨🏻"),
      const UnicodeEmoji("👨🏿‍❤️‍👨🏼"),
      const UnicodeEmoji("👨🏿‍❤️‍👨🏽"),
      const UnicodeEmoji("👨🏿‍❤️‍👨🏾"),
      const UnicodeEmoji("👨🏿‍❤️‍👨🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👩‍❤️‍👩"), [
      const UnicodeEmoji("👩‍❤️‍👩"),
      const UnicodeEmoji("👩🏻‍❤️‍👩🏻"),
      const UnicodeEmoji("👩🏻‍❤️‍👩🏼"),
      const UnicodeEmoji("👩🏻‍❤️‍👩🏽"),
      const UnicodeEmoji("👩🏻‍❤️‍👩🏾"),
      const UnicodeEmoji("👩🏻‍❤️‍👩🏿"),
      const UnicodeEmoji("👩🏼‍❤️‍👩🏻"),
      const UnicodeEmoji("👩🏼‍❤️‍👩🏼"),
      const UnicodeEmoji("👩🏼‍❤️‍👩🏽"),
      const UnicodeEmoji("👩🏼‍❤️‍👩🏾"),
      const UnicodeEmoji("👩🏼‍❤️‍👩🏿"),
      const UnicodeEmoji("👩🏽‍❤️‍👩🏻"),
      const UnicodeEmoji("👩🏽‍❤️‍👩🏼"),
      const UnicodeEmoji("👩🏽‍❤️‍👩🏽"),
      const UnicodeEmoji("👩🏽‍❤️‍👩🏾"),
      const UnicodeEmoji("👩🏽‍❤️‍👩🏿"),
      const UnicodeEmoji("👩🏾‍❤️‍👩🏻"),
      const UnicodeEmoji("👩🏾‍❤️‍👩🏼"),
      const UnicodeEmoji("👩🏾‍❤️‍👩🏽"),
      const UnicodeEmoji("👩🏾‍❤️‍👩🏾"),
      const UnicodeEmoji("👩🏾‍❤️‍👩🏿"),
      const UnicodeEmoji("👩🏿‍❤️‍👩🏻"),
      const UnicodeEmoji("👩🏿‍❤️‍👩🏼"),
      const UnicodeEmoji("👩🏿‍❤️‍👩🏽"),
      const UnicodeEmoji("👩🏿‍❤️‍👩🏾"),
      const UnicodeEmoji("👩🏿‍❤️‍👩🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🫄"), [
      const UnicodeEmoji("🫄"),
      const UnicodeEmoji("🫄🏻"),
      const UnicodeEmoji("🫄🏼"),
      const UnicodeEmoji("🫄🏽"),
      const UnicodeEmoji("🫄🏾"),
      const UnicodeEmoji("🫄🏿"),
      const UnicodeEmoji("🤰"),
      const UnicodeEmoji("🤰🏻"),
      const UnicodeEmoji("🤰🏼"),
      const UnicodeEmoji("🤰🏽"),
      const UnicodeEmoji("🤰🏾"),
      const UnicodeEmoji("🤰🏿"),
      const UnicodeEmoji("🫃"),
      const UnicodeEmoji("🫃🏻"),
      const UnicodeEmoji("🫃🏼"),
      const UnicodeEmoji("🫃🏽"),
      const UnicodeEmoji("🫃🏾"),
      const UnicodeEmoji("🫃🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🤱"), [
      const UnicodeEmoji("🤱"),
      const UnicodeEmoji("🤱🏻"),
      const UnicodeEmoji("🤱🏼"),
      const UnicodeEmoji("🤱🏽"),
      const UnicodeEmoji("🤱🏾"),
      const UnicodeEmoji("🤱🏿"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("🧑‍🍼"), [
      const UnicodeEmoji("🧑‍🍼"),
      const UnicodeEmoji("🧑🏻‍🍼"),
      const UnicodeEmoji("🧑🏼‍🍼"),
      const UnicodeEmoji("🧑🏽‍🍼"),
      const UnicodeEmoji("🧑🏾‍🍼"),
      const UnicodeEmoji("🧑🏿‍🍼"),
      const UnicodeEmoji("👩‍🍼"),
      const UnicodeEmoji("👩🏻‍🍼"),
      const UnicodeEmoji("👩🏼‍🍼"),
      const UnicodeEmoji("👩🏽‍🍼"),
      const UnicodeEmoji("👩🏾‍🍼"),
      const UnicodeEmoji("👩🏿‍🍼"),
      const UnicodeEmoji("👨‍🍼"),
      const UnicodeEmoji("👨🏻‍🍼"),
      const UnicodeEmoji("👨🏼‍🍼"),
      const UnicodeEmoji("👨🏽‍🍼"),
      const UnicodeEmoji("👨🏾‍🍼"),
      const UnicodeEmoji("👨🏿‍🍼"),
    ],
  ),
  const EmojiCategoryItem(
    const UnicodeEmoji("👪"), [
      const UnicodeEmoji("👪"),
      const UnicodeEmoji("👨‍👩‍👦"),
      const UnicodeEmoji("👨‍👩‍👧"),
      const UnicodeEmoji("👨‍👩‍👧‍👦"),
      const UnicodeEmoji("👨‍👩‍👦‍👦"),
      const UnicodeEmoji("👨‍👩‍👧‍👧"),
      const UnicodeEmoji("👨‍👨‍👦"),
      const UnicodeEmoji("👨‍👨‍👧"),
      const UnicodeEmoji("👨‍👨‍👧‍👦"),
      const UnicodeEmoji("👨‍👨‍👦‍👦"),
      const UnicodeEmoji("👨‍👨‍👧‍👧"),
      const UnicodeEmoji("👨‍👦"),
      const UnicodeEmoji("👨‍👧"),
      const UnicodeEmoji("👨‍👧‍👦"),
      const UnicodeEmoji("👨‍👦‍👦"),
      const UnicodeEmoji("👨‍👧‍👧"),
      const UnicodeEmoji("👩‍👩‍👦"),
      const UnicodeEmoji("👩‍👩‍👧"),
      const UnicodeEmoji("👩‍👩‍👧‍👦"),
      const UnicodeEmoji("👩‍👩‍👦‍👦"),
      const UnicodeEmoji("👩‍👩‍👧‍👧"),
      const UnicodeEmoji("👩‍👦"),
      const UnicodeEmoji("👩‍👧"),
      const UnicodeEmoji("👩‍👧‍👦"),
      const UnicodeEmoji("👩‍👦‍👦"),
      const UnicodeEmoji("👩‍👧‍👧"),
    ],
  ),
];
